config/routes.rb
Rails.application.routes.draw do

  root to: 'home#index'
  get 'admin/index'
  get 'admin/confirm_first_product_deliverd'
  post 'admin/admin_login'
  post 'admin/create'
  post 'admin/search_users_by_username'
  post '/admin/update_slider_images'
  post '/admin/search_admins_by_username'
  patch 'admin/reset_password'
  match '/admin_login', :to => 'admin#login', :via => 'get'
  match '/admin_signup', :to => 'admin#new', :via => 'get'
  match '/admin_signout', :to => 'admin#destroy', :via => 'get'
  match '/admin_index', :to => 'admin#index', :via => 'get'
  match '/admin/search_users', :to => 'admin#search_users', :via => 'get'
  match '/admin/reset_user_password', :to => 'admin#reset_user_password', :via => 'get'
  match '/admin_store_categories', :to => 'store#store_categories', :via => 'get'
  match '/admin_store_sub_categories', :to => 'store#sub_categories', :via => 'get'
  match '/admin_store_products', :to => 'store#products', :via => 'get'
  match '/admin_store_selected_product', :to => 'store#product', :via => 'get'
  match '/admin/choose_action', :to => 'admin#user_actions', :via => 'get'
  match '/admin/user_expenses', :to => 'admin#user_expenses', :via => 'get'
  match '/users_first_products', :to=> 'admin#users_first_products', :via => 'get'
  patch '/admin/generate_code'
  match '/admin/codes', :to => 'admin#codes', :via => 'get'
  match '/slider_images', :to => 'admin#slider_images', :via => 'get'
  match '/calculations', :to => 'admin#calculations', :via => 'get'
  patch '/admin/update_calculations'
  match '/admin_actions', :to => 'admin#admin_actions', :via => 'get'
  match '/search_admins', :to => 'admin#search_admins', :via => 'get'
  match '/edit_info', :to => 'admin#edit_info', :via => 'get'
  match '/update_sub_admin', :to => 'admin#update_sub_admin', :via => 'get'
  match '/update_super_admin', :to => 'admin#update_super_admin', :via => 'get'
  patch '/admin/update_sub_admin_info'
  patch '/admin/update_super_admin_info'
  patch '/admin/reset_super_admin_password'
  patch '/admin/reset_sub_admin_password'
  match '/all_sub_admins', :to => 'admin#all_sub_admins', :via => 'get'
  match '/view_sub_admin', :to => 'admin#view_sub_admin', :via => 'post'
  match '/admin/view_searched_user', :to => 'admin#view_searched_user', :via => 'post'
  match '/admin/edit_searched_user', :to => 'admin#edit_searched_user', :via => 'post'
  post 'admin/update_searched_user_info'
  match '/admin/update_governorates', :to => 'user#update_governorates', :via => 'get'
  match '/admin/update_regions', :to => 'user#update_regions', :via => 'get'

  match '/products_orders',:to=>'admin#confirm_products_order', :via => 'get'
  get 'admin/confirm_products_order_deliverd'

  match '/store_categories' , :to => 'application#store_categories', :via => 'get'
  match '/store_products', :to => 'application#products', :via => 'get'
  match '/store_selected_product', :to => 'application#product', :via => 'get'
  match '/store_sub_categories', :to => 'application#store_sub_categories', :via => 'get'

  get 'home/index'

  post 'place/create_country'
  post 'place/create_governorate'
  post 'place/create_region'
  match '/place', :to => 'place#index', :via => 'get'
  match '/add_country', :to => 'place#add_country', :via => 'get'
  match '/add_governorate', :to => 'place#add_governorate', :via => 'get'
  match '/add_region', :to => 'place#add_region', :via => 'get'
  get 'place/index'
  get 'place/add_country'
  get 'place/add_governorate'
  get 'place/add_region'
  get 'store/index'
  patch 'place/update_region'
  match '/countries', :to => 'place#countries', :via => 'get'
  match '/governorates', :to => 'place#governorates', :via => 'get'
  match '/regions', :to => 'place#regions', :via => 'get'
  match '/selected_region', :to => 'place#region', :via => 'get'
  patch 'place/update_country'
  patch 'place/update_governorate'
  match '/place/update_governorates', :to => 'user#update_governorates', :via => 'get'
  match '/place/update_regions', :to => 'user#update_regions', :via => 'get'

  match '/add_product_order', :to => 'product_order#add_product_order', :via => 'get'
  match '/add_product_order', :to => 'product_order#add_product_order_old_customer', :via => 'get'
  post 'product_order/create_product_order'
  post 'product_order/create_product_order_old_customer'
  match '/add_product_order', :to => 'product_order#add_product_order', :via => 'get'
  post 'product_order/create_product_order'
  match '/empty_cart', :to => 'product_order#empty_cart', :via => 'post'
  post 'product_order/empty_cart'
  match '/add_to_cart', :to => 'product_order#add_to_cart', :via => 'post'
  post 'product_order/add_to_cart'
  match '/remove_product_from_cart', :to => 'product_order#remove_product_from_cart', :via => 'get'
  get 'product_order/remove_product_from_cart'

  get 'profile/index'
  match '/profile', :to => 'profile#index', :via => 'get'
  match '/user_order', :to => 'profile#product_credit_order', :via => 'get'
  match '/generate_code', :to => 'profile#generate_code', :via => 'post'
  post 'profile/generate_code'
  match '/get_left', :to => 'profile#get_left', :via => 'get'
  match '/get_parent', :to => 'profile#get_parent', :via => 'get'
  match '/get_right', :to => 'profile#get_right', :via => 'get'
  get 'profile/get_left'
  get 'profile/get_parent'
  get 'profile/get_right'

  get 'session/new'
  post 'session/create'
  match '/signin', :to => 'session#new', :via => 'get'
  match '/signout', :to => 'session#destroy', :via => 'get'

  get 'store/add_category'
  get 'store/add_sub_category'
  get 'store/add_product'
  post 'store/create_category'
  post 'store/create_sub_category'
  post 'store/create_product'
  match '/store', :to => 'store#index', :via => 'get'
  match '/add_category', :to => 'store#add_category', :via => 'get'
  match '/add_sub_category', :to => 'store#add_sub_category', :via => 'get'
  match '/add_product', :to => 'store#add_product', :via => 'get'
  patch 'store/update_product'
  patch 'store/update_category_name'
  patch 'store/update_sub_category_name'
  match '/store/all_products', :to => 'store#all_products', :via => 'get'

  get 'user/show'
  get 'user/new'
  get 'user/edit_info'
  get 'user/index'
  get 'user/change_password'
  get 'user/show'
  post 'user/create'
  match '/create', :to=>'user#create',:via=>'post'
  match '/verify_email_create', :to=>'user#verify_email_create',:via=>'post'
  post 'user/index'
  patch 'user/update_user_info'
  patch 'user/update_password'
  match '/signUp', :to => 'user#sign_up', :via => 'get'
  match '/edit_profile', :to => 'user#edit_info', :via => 'get'
  match '/change_password', :to => 'user#change_password', :via => 'get'
  match '/verify_email', :to => 'user#verify_email_create', :via => 'post'
  match '/verify_email', :to => 'user#verify_email', :via => 'get'
  match '/forgetPassword', :to => 'user#forget_password', :via => 'get'
  match '/send_new_password', :to => 'user#send_new_password', :via => 'post'
  match '/expenses', :to => 'user#expenses', :via => 'get'
  match '/first_product', :to => 'user#first_product', :via => 'get'
  get '/user/select_first_product'
  match '/update_governorates', :to => 'user#update_governorates', :via => 'get'
  match '/update_regions', :to => 'user#update_regions', :via => 'get'
  match '/user/update_governorates', :to => 'user#update_governorates', :via => 'get'
  match '/user/update_regions', :to => 'user#update_regions', :via => 'get'

  get '/about_us',:to => 'home#about_us', :via => 'get'
  get '/contact_us',:to => 'home#contact_us', :via => 'get'
  get '/delivery_information',:to => 'home#delivery_information', :via => 'get'
  get '/terms_conditions',:to => 'home#terms_conditions', :via => 'get'
  get '/privacy_policy',:to => 'home#privacy_policy', :via => 'get'

  match '*not_found', to: 'errors#error_404', via: :all

end

app/views/admin/_admin_search_by_username.html.erb
<center>
  <% flash.each do |key, value| %>
      <% id= (key=="success") ? "success_messages" : "error_explanation" %>
      <div id=<%= id %>>
        <h2><%= value %></h2>
      </div>
  <% end %>
  <h1>Enter a username for admin to search for </h1>

  <div>
    <%= form_for @sub_admin, url: {action: "search_admins_by_username"}, :remote => true do |f| %>
        <div class="content">
          <b> <%= f.label :username %></b> :
          <%= f.text_field :username %>
          <%= f.submit "search", :class => "button" %>
        </div>
    <% end %>
  </div>
</center>

app/views/admin/_all_sub_admins.html.erb
<center>
  <div id="sub_admins_div">
    <% flash.each do |key, value| %>
        <% id= (key=="success") ? "success_messages" : "error_explanation" %>
        <div id=<%= id %>>
          <h2><%= value %></h2>
        </div>
    <% end %>
    <% if @all_sub_admins && @all_sub_admins.count>0 %>
        <h1>Sub admins </h1>
        <% @all_sub_admins.each do |sub_admin| %>
            <div class="backs">


              <%= link_to "view_sub_admin?sub_admin_id=#{sub_admin.id}", {:controller => "admin", :action => "view_sub_admin", :sub_admin_id => sub_admin.id, :method => "post", :remote => true} do %>
                  <div class="button_bases b1_skewed_slide_in">
                    <div><%= sub_admin.username %></div>
                    <div></div>
                    <div><%= sub_admin.username %></div>
                  </div>
              <% end %>
            </div>
        <% end %>
        <!--Pagination Part Start-->
        <div class="flickr_pagination">
          <%= will_paginate @all_sub_admins %>
        </div>
        <!--Pagination Part End-->
    <% else %>
        <h1> No Sub admins on system </h1>

        <div class="back">
          <a href=<%= admin_signup_path %>>
            <div class="button_base b_3d_double_roll">
              <div>Create New Admin</div>
              <div>Create New Admin</div>
              <div>Create New Admin</div>
              <div>Create New Admin</div>
            </div>
          </a>
        </div>
    <% end %>
  </div>
</center>

app/views/admin/_edit_searched_user.html.erb
<center>
  <% flash.each do |key, value| %>
      <% id= (key=="success") ? "success_messages" : "error_explanation" %>
      <div id=<%= id %>>
        <h2><%= value %></h2>
      </div>
  <% end %>
  <% if @user && @user.errors.full_messages.any? %>
      <div id="error_explanation">
        <% @user.errors.full_messages.each do |error_message| %>
            <h2><%= error_message if @user.errors.full_messages.first == error_message %></h2>
        <% end %>
      </div>
  <% end %>
  <% if @user_info && @user_info.errors.full_messages.any? %>
      <div id="error_explanation">
        <% @user_info.errors.full_messages.each do |error_message| %>
            <h2><%= error_message if @user_info.errors.full_messages.first == error_message %></h2>
        <% end %>
      </div>
  <% end %>
  <h1>Edit User info</h1>

  <%= form_tag ({controller: "admin", action: "update_searched_user_info"}), method: "post", remote: true do |f| %>

      <table>
        <tr>
          <td><h3>Username </h3></td>
          <td> : <%= text_field :user, :username %> </td>
        </tr>
        <tr>
          <td>
            <br/>
          </td>
        </tr>
        <tr>
          <td><h3>Master credit</h3></td>
          <td> :<%= number_field :user, :master_credit %> </td>
        </tr>
        <tr>
          <td>
            <br/>
          </td>
        </tr>
        <tr>
          <td><h3>Product credit</td>
          <td> : <%= number_field :user, :product_credit, in: 0.0..100000000.0 %> </td>
        </tr>
        <tr>
          <td>
            <br/>
          </td>
        </tr>
        <tr>
          <td><h3>First name</td>
          <td> :<%= text_field :user_info, :first_name %> </td>
        </tr>
        <tr>
          <td>
            <br/>
          </td>
        </tr>
        <tr>
          <td><h3>Last name</td>
          <td> :<%= text_field :user_info, :last_name %> </td>
        </tr>
        <tr>
          <td>
            <br/>
          </td>
        </tr>
        <tr>
          <td><h3>Email</td>
          <td> : <%= text_field :user_info, :email %> </td>
        </tr>
        <tr>
          <td>
            <br/>
          </td>
        </tr>
        <tr>
          <td><h3>Mobile</td>
          <td> : <%= number_field :user_info, :mobile %> </td>
        </tr>

        <tr>
          <td>
            <br/>
          </td>
        </tr>
        <tr>
          <td><h3>Land phone</td>
          <td> : <%= number_field :user_info, :land_phone %> </td>
        </tr>
        <tr>
          <td><h3>Address1</td>
          <td> :<%= text_area :user_info, :address1 %> </td>
        </tr>
        <tr>
          <td>
            <br/>
          </td>
        </tr>
        <tr>
          <td><h3>Address2</td>
          <td> :<%= text_area :user_info, :address2 %> </td>
        </tr>
        <tr>
          <td>
            <br/>
          </td>
        </tr>
        <tr>
          <td><h3>Postal code</td>
          <td> : <%= number_field :user_info, :postal_code %> </td>
        </tr>
        <tr>
          <td><h3>National id </h3></td>
          <td> : <%= number_field :user_info, :national_id %> </td>

        </tr>
        <tr>
          <td><h3>Birthdate</td>
          <td> :<%= date_field :user_info, :birthdate %> </td>
        </tr>
        <tr>
          <td>
            <br/>
          </td>
        </tr>
        <tr>
          <td><h3>Gender</td>
          <td>Male :
            <%= radio_button :user_info, :gender, 'true', :checked => true %>Female
            :<%= radio_button :user_info, :gender, 'false' %> </td>
        </tr>
        <tr>
          <td>
            <br/>
          </td>
        </tr>
        <tr>
          <td><h3>Social status </h3></td>
          <td>
            :   <%= collection_select :user_info, :status_id, Status.order(:name), :id, :name, including_blank: true %> </td>
        </tr>
        <tr>
          <td><h3>Country </h3></td>
          <td>
            : <%= select :user_info, :country_id, options_for_select(@countries.collect { |country| [country.name.titleize, country.id] }, 1), {}, {id: 'countries_select'} %> </td>
        </tr>
        <tr>
          <td><h3>Governorate </h3></td>
          <td>
            : <%= select :user_info, :governorate_id, options_for_select(@governorates.collect { |governorate| [governorate.name.titleize, governorate.id] }, 0), {}, {id: 'governorates_select'} %> </td>
        </tr>
        <tr>
          <td><h3>Region </h3></td>
          <td>
            : <%= select :user_info, :region_id, options_for_select(@regions.collect { |region| [region.name.titleize, region.id] }, 0), {}, {id: 'regions_select'} %> </td>
        </tr>
        <tr>
          <td>
            <br/>
          </td>
          <td><%= submit_tag "Update", :class => "button" %></td>
        </tr>
      </table>

  <% end %>
</center>

app/views/admin/_generated_codes.html.erb
<h1>Used Codes</h1>
<table id="fourth-box-table">
  <tr>
    <th>Code</th>
    <th>Is valid</th>
  </tr>
  <% @used_codes.each do |code| %>
      <tr>
        <td><%= code.code %></td>
        <td><%= code.valid %></td>
      </tr>
  <% end %>
</table>
<br/>
<h1>Un used Codes</h1>
<table id="fourth-box-table">
  <tr>
    <th>Code</th>
    <th>Is valid</th>
  </tr>
  <% @unused_codes.each do |code| %>
      <tr>
        <td><%= code.code %></td>
        <td><%= code.valid %></td>
      </tr>
  <% end %>
</table>
<br/>
<% flash.each do |key, value| %>
    <% id= (key=="success") ? "success_messages" : "error_explanation" %>
    <div id=<%= id %>>
      <h2><%= value %></h2>
    </div>
<% end %>
<%= form_for @current_admin, url: {action: "generate_code"}, :remote => true do |f| %>
    <table>
      <tr>
        <td><h3>password </h3></td>
        <td>: <%= f.password_field :conf_pass_for_gen_code %></td>
        <td> <%= f.submit "generate code", :class => "button",
                          data: {confirm: "Do you want to generate code ?"} %></td>
      </tr>
    </table>
<% end %>
<br/>

app/views/admin/_view_searched_user.html.erb
<center>
  <% flash.each do |key, value| %>
      <% id= (key=="success") ? "success_messages" : "error_explanation" %>
      <div id=<%= id %>>
        <h2><%= value %></h2>
      </div>
  <% end %>
  <h1>Choose Action for <%= @searched_user.username %> </h1>

  <div class="backs">
    <a href=<%= admin_user_expenses_path %>>
      <div class="button_bases b1_skewed_slide_in">
        <div>User Expenses</div>
        <div></div>
        <div>User Expenses</div>
      </div>
    </a>
  </div>
  <div class="backs">
    <a href=<%= admin_reset_user_password_path %>>
      <div class="button_bases b1_skewed_slide_in">
        <div>Reset Password</div>
        <div></div>
        <div>Reset Password</div>
      </div>
    </a>
  </div>
  <div class="backs">
    <%= link_to admin_edit_searched_user_path, method: "post", remote: true do %>
        <div class="button_bases b1_skewed_slide_in">
          <div>Edit user info</div>
          <div></div>
          <div>Edit user info</div>
        </div>
    <% end %>
  </div>
</center>

app/views/admin/all_sub_admins.html.erb
<div id="admin_view_edit">
  <%=render "all_sub_admins"%>
</div>

app/views/admin/edit_searched_user.js.erb
$("#search_users_div").html("<%= escape_javascript(render "edit_searched_user") %>");

app/views/admin/generate_code.js.erb
$("#generated_code").html("<%= escape_javascript(render "generated_codes") %>");

app/views/admin/index.html.erb
<center>
  <% flash.each do |key, value| %>
      <% id= (key=="success") ? "success_messages" : "error_explanation" %>
      <div id=<%= id %>>
        <h2><%= value %></h2>
      </div>
  <% end %>
</center>
<h1>Welcome <%= @admin.username %>  </h1>
<div id="all_boxes">

  <% if @amdin_is_super %>
      <div class="back">
        <a href=<%= admin_signup_path %>>
          <div class="button_base b_3d_double_roll">
            <div>Create New Admin</div>
            <div>Create New Admin</div>
            <div>Create New Admin</div>
            <div>Create New Admin</div>
          </div>
        </a>
      </div>
  <% end %>
  <% if @amdin_is_super %>
      <div class="back">
        <a href=<%= admin_actions_path %>>
          <div class="button_base b_3d_double_roll">
            <div> Admins</div>
            <div>Admins</div>
            <div>Admins</div>
            <div>Admins</div>
          </div>
        </a>
      </div>
  <% end %>

  <% if @amdin_is_super ||@admin_can_reset_password %>
      <div class="back">
        <a href=<%= admin_search_users_path %>>
          <div class="button_base b_3d_double_roll">
            <div> Users</div>
            <div> Users</div>
            <div> Users</div>
            <div> Users</div>
          </div>
        </a>
      </div>
  <% end %>

  <% if @amdin_is_super ||@admin_can_add_product %>
      <div class="back">
        <a href=<%= store_path %>>
          <div class="button_base b_3d_double_roll">
            <div> Store</div>
            <div> Store</div>
            <div> Store</div>
            <div> Store</div>
          </div>
        </a>
      </div>
  <% end %>


  <% if @amdin_is_super || @admin_can_add_place %>
      <div class="back">
        <a href=<%= place_path %>>
          <div class="button_base b_3d_double_roll">
            <div>Places</div>
            <div>Places</div>
            <div>Places</div>
            <div>Places</div>
          </div>
        </a>
      </div>
  <% end %>


  <% if @amdin_is_super || @admin_can_generate_codes %>
      <div class="back">
        <a href=<%= admin_codes_path %>>
          <div class="button_base b_3d_double_roll">
            <div> Generate code</div>
            <div> Generate code</div>
            <div> Generate code</div>
            <div> Generate code</div>
          </div>
        </a>
      </div>
  <% end %>

  <% if @amdin_is_super || @admin_can_add_product %>
      <div class="back">
        <a href=<%= store_all_products_path %>>
          <div class="button_base b_3d_double_roll">
            <div> View products</div>
            <div> View products</div>
            <div> View products</div>
            <div> View products</div>
          </div>
        </a>
      </div>
  <% end %>


  <% if @amdin_is_super %>
      <div class="back">
        <a href=<%= slider_images_path %>>
          <div class="button_base b_3d_double_roll">
            <div> Slider Images</div>
            <div> Slider Images</div>
            <div> Slider Images</div>
            <div> Slider Images</div>
          </div>
        </a>
      </div>
  <% end %>


  <% if @amdin_is_super %>
      <div class="back">
        <a href=<%= calculations_path %>>
          <div class="button_base b_3d_double_roll">
            <div> Update Calculaions</div>
            <div> Update Calculaions</div>
            <div> Update Calculaions</div>
            <div> Update Calculaions</div>
          </div>
        </a>
      </div>
  <% end %>


  <% if @amdin_is_super || @admin_can_add_product %>
      <div class="back">
        <a href=  <%= users_first_products_path %>>
          <div class="button_base b_3d_double_roll">
            <div> Completed first products</div>
            <div> Completed first products</div>
            <div> Completed first products</div>
            <div> Completed first products</div>
          </div>
        </a>
      </div>
  <% end %>

  <% if @amdin_is_super || @admin_can_add_product %>
      <div class="back">
        <a href=  <%= products_orders_path %>>
          <div class="button_base b_3d_double_roll">
            <div> Confirm products order</div>
            <div> Confirm products order</div>
            <div> Confirm products order</div>
            <div> Confirm products order</div>
          </div>
        </a>
      </div>
  <% end %>
</div>

app/views/admin/login.html.erb
<center>
  <% flash.each do |key, value| %>
      <% id= (key=="success") ? "success_messages" : "error_explanation" %>
      <div id=<%= id %>>
        <h2><%= value %></h2>
      </div>
  <% end %>
  <h1>Log in as admin</h1>
  <%= form_for Admin.new, url: {action: "admin_login"} do |f| %>
      <div class="content">
        <table>
          <tr>
            <td><h3>Admin </h3></td>
            <td> : <%= f.text_field :username %> </td>
          </tr>
          <tr>
            <td><br/></td>
          </tr>
          <tr>
            <td><h3>Password </h3></td>
            <td>
              :<%= f.password_field :password %>

            </td>
          </tr>
        </table>
        <%= f.submit "Log in", :class => "button" %>
      </div>
  <% end %>
</center>

app/views/admin/new.html.erb
<center>
  <% flash.each do |key, value| %>
      <% id= (key=="success") ? "success_messages" : "error_explanation" %>
      <div id=<%= id %>>
        <h2><%= value %></h2>
      </div>
  <% end %>
  <% if @new_admin && @new_admin.errors.full_messages.any? %>
      <div id="error_explanation">
        <% @new_admin.errors.full_messages.each do |error_message| %>
            <h2><%= error_message if @new_admin.errors.full_messages.first == error_message %></h2>
        <% end %>
      </div>
  <% end %>
  <h1>Create a new admin</h1>
  <%= form_for @new_admin, url: {controller: "admin", action: "create"} do |f| %>

      <div class="content">
        <table>
          <tbody>
          <tr>
            <td><h3>User Name</h3></td>
            <td> : <%= f.text_field :username %> </td>
          </tr>
          <tr>

            <td><h3>Password</h3></td>
            <td> : <%= f.password_field :password %> </td>
          </tr>
          <tr>
            <td><h3>Confirm Password</h3></td>
            <td> : <%= f.password_field :password_confirmation %> </td>

          </tr>
          <tr>
            <td><h3>Email</h3></td>
            <td> : <%= f.text_field :email %> </td>

          </tr>
          <tr>
            <td><h3>First Name</h3></td>
            <td> : <%= f.text_field :first_name %> </td>

          </tr>
          <tr>
            <td><h3>Last Name</h3></td>
            <td> : <%= f.text_field :last_name %> </td>

          </tr>
          <tr>
            <td><h3>Adress</h3></td>
            <td> : <%= f.text_area :address, :cols => "5", :rows => "5" %> </td>

          </tr>
          <tr>
            <td><h3>Mobile</h3></td>
            <td> : <%= f.number_field :mobile %> </td>

          </tr>

          <tr>
            <td><h3>Priveleges</h3></td>
            <td> :
              <table>
                <tr>
                  <td> Can reset users passwords : <%= f.check_box :can_reset_password %> </td>
                </tr>
                <tr>
                  <td> Can generate codes : <%= f.check_box :can_generate_code %> </td>
                </tr>
                <tr>
                  <td> Can add products : <%= f.check_box :can_add_product %> </td>
                </tr>
                <tr>
                  <td> Can add places : <%= f.check_box :can_add_place %> </td>
                </tr>
              </table>
            </td>
          </tr>

          <tr>
            <td></td>
            <td>
              <br/>
              <%= f.submit 'Create New Admin', :class => "button" %></td>
          </tr>
          </tbody>
        </table>
      </div>
  <% end %>
</center>

app/views/admin/update_sub_admin_info.js.erb
$("#admin_view_edit").html("<%= escape_javascript(render "update_sub_admin") %>");