config/routes.rb
Rails.application.routes.draw do

  root to: 'home#index'
  get 'admin/index'
  get 'admin/confirm_first_product_deliverd'
  post 'admin/admin_login'
  post 'admin/create'
  post 'admin/search_users_by_username'
  post '/admin/update_slider_images'
  post '/admin/search_admins_by_username'
  patch 'admin/reset_password'
  match '/admin_login', :to => 'admin#login', :via => 'get'
  match '/admin_signup', :to => 'admin#new', :via => 'get'
  match '/admin_signout', :to => 'admin#destroy', :via => 'get'
  match '/admin_index', :to => 'admin#index', :via => 'get'
  match '/admin/search_users', :to => 'admin#search_users', :via => 'get'
  match '/admin/reset_user_password', :to => 'admin#reset_user_password', :via => 'get'
  match '/admin_store_categories', :to => 'store#store_categories', :via => 'get'
  match '/admin_store_sub_categories', :to => 'store#sub_categories', :via => 'get'
  match '/admin_store_products', :to => 'store#products', :via => 'get'
  match '/admin_store_selected_product', :to => 'store#product', :via => 'get'
  match '/admin/choose_action', :to => 'admin#user_actions', :via => 'get'
  match '/admin/user_expenses', :to => 'admin#user_expenses', :via => 'get'
  match '/users_first_products', :to=> 'admin#users_first_products', :via => 'get'
  patch '/admin/generate_code'
  match '/admin/codes', :to => 'admin#codes', :via => 'get'
  match '/slider_images', :to => 'admin#slider_images', :via => 'get'
  match '/calculations', :to => 'admin#calculations', :via => 'get'
  patch '/admin/update_calculations'
  match '/admin_actions', :to => 'admin#admin_actions', :via => 'get'
  match '/search_admins', :to => 'admin#search_admins', :via => 'get'
  match '/edit_info', :to => 'admin#edit_info', :via => 'get'
  match '/update_sub_admin', :to => 'admin#update_sub_admin', :via => 'get'
  match '/update_super_admin', :to => 'admin#update_super_admin', :via => 'get'
  patch '/admin/update_sub_admin_info'
  patch '/admin/update_super_admin_info'
  patch '/admin/reset_super_admin_password'
  patch '/admin/reset_sub_admin_password'
  match '/all_sub_admins', :to => 'admin#all_sub_admins', :via => 'get'
  match '/view_sub_admin', :to => 'admin#view_sub_admin', :via => 'post'
  match '/admin/view_searched_user', :to => 'admin#view_searched_user', :via => 'post'
  match '/admin/edit_searched_user', :to => 'admin#edit_searched_user', :via => 'post'
  post 'admin/update_searched_user_info'
  match '/admin/update_governorates', :to => 'user#update_governorates', :via => 'get'
  match '/admin/update_regions', :to => 'user#update_regions', :via => 'get'

  match '/products_orders',:to=>'admin#confirm_products_order', :via => 'get'
  get 'admin/confirm_products_order_deliverd'

  match '/store_categories' , :to => 'application#store_categories', :via => 'get'
  match '/store_products', :to => 'application#products', :via => 'get'
  match '/store_selected_product', :to => 'application#product', :via => 'get'
  match '/store_sub_categories', :to => 'application#store_sub_categories', :via => 'get'

  get 'home/index'

  post 'place/create_country'
  post 'place/create_governorate'
  post 'place/create_region'
  match '/place', :to => 'place#index', :via => 'get'
  match '/add_country', :to => 'place#add_country', :via => 'get'
  match '/add_governorate', :to => 'place#add_governorate', :via => 'get'
  match '/add_region', :to => 'place#add_region', :via => 'get'
  get 'place/index'
  get 'place/add_country'
  get 'place/add_governorate'
  get 'place/add_region'
  get 'store/index'
  patch 'place/update_region'
  match '/countries', :to => 'place#countries', :via => 'get'
  match '/governorates', :to => 'place#governorates', :via => 'get'
  match '/regions', :to => 'place#regions', :via => 'get'
  match '/selected_region', :to => 'place#region', :via => 'get'
  patch 'place/update_country'
  patch 'place/update_governorate'
  match '/place/update_governorates', :to => 'user#update_governorates', :via => 'get'
  match '/place/update_regions', :to => 'user#update_regions', :via => 'get'

  match '/add_product_order', :to => 'product_order#add_product_order', :via => 'get'
  match '/add_product_order', :to => 'product_order#add_product_order_old_customer', :via => 'get'
  post 'product_order/create_product_order'
  post 'product_order/create_product_order_old_customer'
  match '/add_product_order', :to => 'product_order#add_product_order', :via => 'get'
  post 'product_order/create_product_order'
  match '/empty_cart', :to => 'product_order#empty_cart', :via => 'post'
  post 'product_order/empty_cart'
  match '/add_to_cart', :to => 'product_order#add_to_cart', :via => 'post'
  post 'product_order/add_to_cart'
  match '/remove_product_from_cart', :to => 'product_order#remove_product_from_cart', :via => 'get'
  get 'product_order/remove_product_from_cart'

  get 'profile/index'
  match '/profile', :to => 'profile#index', :via => 'get'
  match '/user_order', :to => 'profile#product_credit_order', :via => 'get'
  match '/generate_code', :to => 'profile#generate_code', :via => 'post'
  post 'profile/generate_code'
  match '/get_left', :to => 'profile#get_left', :via => 'get'
  match '/get_parent', :to => 'profile#get_parent', :via => 'get'
  match '/get_right', :to => 'profile#get_right', :via => 'get'
  get 'profile/get_left'
  get 'profile/get_parent'
  get 'profile/get_right'

  get 'session/new'
  post 'session/create'
  match '/signin', :to => 'session#new', :via => 'get'
  match '/signout', :to => 'session#destroy', :via => 'get'

  get 'store/add_category'
  get 'store/add_sub_category'
  get 'store/add_product'
  post 'store/create_category'
  post 'store/create_sub_category'
  post 'store/create_product'
  match '/store', :to => 'store#index', :via => 'get'
  match '/add_category', :to => 'store#add_category', :via => 'get'
  match '/add_sub_category', :to => 'store#add_sub_category', :via => 'get'
  match '/add_product', :to => 'store#add_product', :via => 'get'
  patch 'store/update_product'
  patch 'store/update_category_name'
  patch 'store/update_sub_category_name'
  match '/store/all_products', :to => 'store#all_products', :via => 'get'

  get 'user/show'
  get 'user/new'
  get 'user/edit_info'
  get 'user/index'
  get 'user/change_password'
  get 'user/show'
  post 'user/create'
  match '/create', :to=>'user#create',:via=>'post'
  match '/verify_email_create', :to=>'user#verify_email_create',:via=>'post'
  post 'user/index'
  patch 'user/update_user_info'
  patch 'user/update_password'
  match '/signUp', :to => 'user#sign_up', :via => 'get'
  match '/edit_profile', :to => 'user#edit_info', :via => 'get'
  match '/change_password', :to => 'user#change_password', :via => 'get'
  match '/verify_email', :to => 'user#verify_email_create', :via => 'post'
  match '/verify_email', :to => 'user#verify_email', :via => 'get'
  match '/forgetPassword', :to => 'user#forget_password', :via => 'get'
  match '/send_new_password', :to => 'user#send_new_password', :via => 'post'
  match '/expenses', :to => 'user#expenses', :via => 'get'
  match '/first_product', :to => 'user#first_product', :via => 'get'
  get '/user/select_first_product'
  match '/update_governorates', :to => 'user#update_governorates', :via => 'get'
  match '/update_regions', :to => 'user#update_regions', :via => 'get'
  match '/user/update_governorates', :to => 'user#update_governorates', :via => 'get'
  match '/user/update_regions', :to => 'user#update_regions', :via => 'get'

  get '/about_us',:to => 'home#about_us', :via => 'get'
  get '/contact_us',:to => 'home#contact_us', :via => 'get'
  get '/delivery_information',:to => 'home#delivery_information', :via => 'get'
  get '/terms_conditions',:to => 'home#terms_conditions', :via => 'get'
  get '/privacy_policy',:to => 'home#privacy_policy', :via => 'get'

  match '*not_found', to: 'errors#error_404', via: :all

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  include SessionHelper
  def about_us
  end

  def contact_us
  end

  def delivery_information
  end

  def terms_conditions
  end

  def privacy_policy
  end

  def index
    # if user_is_signed_in?
    # redirect_to profile_path
    # end
    # UserMailer.signUp("proragab@gmail.com","132156").deliver
    slider_images_dir_name="app/assets/images/slider_images"
    if File.exist?(slider_images_dir_name)
      @slider_images=Dir.glob(slider_images_dir_name+"/*").map do |f|
        File.basename f
      end.sort
    else
      @slider_images=Array.new
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
  # return an array of all images file names for a given product
  def get_slider_images
    return Dir.glob("app/assets/images/slider_images/*").map do |f|
                  File.basename f
                   end.sort
  end
end

app/views/home/about_us.html.erb
<div class="wrapper-box">
	<div class="main-wrapper">
		<div id="container">
			<!--Left Part-->
			<div id="column-left">
				<div class="box">
					<div class="box-heading">
						Information
					</div>
					<div class="box-content">
						<ul class="list-item">
							<li>
								<%= link_to "About Us",about_us_path %>
							</li>
							<li>
								<%= link_to "Delivery Information",delivery_information_path %>
							</li>
							<li>
								<%= link_to "Privacy Policy",privacy_policy_path %>
							</li>
							<li>
								<%= link_to "Terms Conditions",terms_conditions_path %>
							</li>
							<li>
								<%= link_to "Contact Us",contact_us_path %>
							</li>
						</ul>
					</div>
				</div>

			</div>
			<!--Left End-->
			<!--Middle Part Start-->
			<div id="content">
				<!--Breadcrumb Part Start-->
				<div class="breadcrumb">
					<%= link_to "Home",root_path %> » <%= link_to "About Us",about_us_path %>
				</div>
				<!--Breadcrumb Part End-->
				<h1>About Us</h1>
								<h4 dir="rtl" class="western" align="left" style="margin-top: 0.17in; margin-bottom: 0.03in; line-height: 100%"><a name="h.cfshb62rljd6"></a>
<font color="#000000"><font face="Arial, serif"><span style="text-decoration: none"><b>About
Smart and New</b></span></font></font></h4>
<p dir="rtl" align="left" style="margin-bottom: 0in; line-height: 115%">
We are SMART AND NEW company for Network marketing and direct selling
, now you can         start your own business , and make money easily
from working with us.</p>
<p dir="rtl" align="left" style="margin-bottom: 0in; line-height: 115%">
<br>
</p>
<p dir="rtl" align="left" style="margin-bottom: 0in; line-height: 115%">
We are the first network marketing company that provides essential
and valuable products that satisfy your needs and your home needs .</p>
<p dir="rtl" align="left" style="margin-bottom: 0in; line-height: 115%">
<br>
</p>
<p dir="rtl" align="left" style="margin-bottom: 0in; line-height: 115%">
We provide valuable products with the same local market prices or
less and that is our smart and new vision of marketing that any other
network marketing company doesn't provide .</p>
<p dir="rtl" align="left" style="margin-bottom: 0in; line-height: 115%">
<br>
</p>
<p dir="rtl" align="left" style="margin-bottom: 0in; line-height: 115%">
with all these advantages in prices and valuable products we see that
all is not enough so we provide a fantastic way to gain money by our
profitable selling system .</p>
<p dir="rtl" align="left" style="margin-bottom: 0in; line-height: 115%">
<br>
</p>
<p dir="rtl" align="left" style="margin-bottom: 0in; line-height: 115%">
Smart and new company is the new vision of marketing .</p>
<p dir="rtl" align="left" style="margin-bottom: 0in; line-height: 115%">
<br>
</p>
<p dir="rtl" align="left" style="margin-bottom: 0in; line-height: 115%">
We provide all essential products that every body need for work , for
life , for homes with the best prices .</p>
<p dir="rtl" align="left" style="margin-bottom: 0in; line-height: 115%">
</p>
<p dir="rtl" align="left" style="margin-bottom: 0in; line-height: 115%">
we work to satisfy our customers by having better life ,  good health
and happiness .</p>
<h4 dir="rtl" class="western" align="left" style="margin-top: 0.17in; margin-bottom: 0.03in; line-height: 100%"><a name="h.tllmi2mgddgj"></a>
<font color="#000000"><font face="Arial, serif"><span style="text-decoration: none">
</h4><h4 dir="rtl" class="western" align="left" style="margin-top: 0.17in; margin-bottom: 0.03in; line-height: 100%"><a name="h.bg5m3r10exnc"></a>
<font color="#000000"><font face="Arial, serif"><span style="text-decoration: none">
	<b>Our
Values</b></span></font></font></h4>
<p dir="rtl" align="left" style="margin-bottom: 0in; line-height: 115%">
					</p>
<ul>
	<li><p dir="rtl" align="left" style="margin-bottom: 0in; line-height: 115%">
	 ACCOUNTABILITY .</p>
	<li><p dir="rtl" align="left" style="margin-bottom: 0in; line-height: 115%">
	 DISCIPLINE .</p>
	<li><p dir="rtl" align="left" style="margin-bottom: 0in; line-height: 115%">
	 COLLABORATION .</p>
	<li><p dir="rtl" align="left" style="margin-bottom: 0in; line-height: 115%">
	 CREDIBILITY .</p>
	<li><p dir="rtl" align="left" style="margin-bottom: 0in; line-height: 115%">
	 COMMUNICATION .</p>
	<li><p dir="rtl" align="left" style="margin-bottom: 0in; line-height: 115%">
	 CUSTOMER ORIENTATION .</p>
	<li><p dir="rtl" align="left" style="margin-bottom: 0in; line-height: 115%">
	 TEAM WORK .</p>
	<li><p dir="rtl" align="left" style="margin-bottom: 0in; line-height: 115%">
	 COMMUNICATION .</p>
	<li><p dir="rtl" align="left" style="margin-bottom: 0in; line-height: 115%">
	 COMMITMENT TO RESULTS .</p>
	<li><p dir="rtl" align="left" style="margin-bottom: 0in; line-height: 115%">
	 PLANNING AND ORGANIZING .</p>
</ul>
<br/>
<br/>

			
			</div>
			<!--Middle Part End-->
			<div class="clear"></div>
		</div>
	</div>
</div>

app/views/home/contact_us.html.erb
<!--Left Part-->
<div id="column-left">
	<div class="box">
		<div class="box-heading">
			Information
		</div>
		<div class="box-content">
			<ul class="list-item">
				<li>
					<%= link_to "About Us",about_us_path %>
				</li>
				<li>
					<%= link_to "Delivery Information",delivery_information_path %>
				</li>
				<li>
					<%= link_to "Privacy Policy",privacy_policy_path %>
				</li>
				<li>
					<%= link_to "Terms Conditions",terms_conditions_path %>
				</li>
				<li>
					<%= link_to "Contact Us",contact_us_path %>
				</li>
			</ul>
		</div>
	</div>
</div>
<div id="content">
	<!--Breadcrumb Part Start-->
	<div class="breadcrumb">
		<%= link_to "Home",root_path %> » <%= link_to "Contact Us",contact_us_path %>
	</div>
	<!--Breadcrumb Part End-->
	<h1>Contact Us</h1>
	<!-- <h2>Our Location</h2>
	<div class="contact-info">
	<div class="content">
	<div class="left">
	<h4><b>Address:</b></h4>
	<p>
	Central Square, 22 Hoi Wing Road, Tuen Mun, New Delhi,
	<br>
	India. 3800004
	</p>
	</div>
	<div class="right">
	<h4><b>Telephone:</b></h4>
	+91 9898989898
	<br>
	+91 8787878787
	<br>
	</div>
	</div>
	</div> -->
	<h2>Contact Form</h2>
	<div class="content">
		<b>First Name:</b>
		<br>
		<input class="large-field" type="text" value="test" name="name">
		<br>
		<br>
		<b>E-Mail Address:</b>
		<br>
		<input class="large-field" type="text" value="test@test.com" name="email">
		<br>
		<br>
		<b>Mobile :</b>
		<br>
		<input class="large-field" type="text" value="0123456789" name="email">dd
		<br>
		<br>
		<b>Message:</b>
		<br>
		<textarea style="width: 98%;" rows="10" cols="40" name="enquiry"></textarea>
	</div>
	<div class="buttons">
		<div class="right">
			<input type="submit" class="button" value="Send">
		</div>
	</div>
</div>


app/views/home/delivery_information.html.erb
<div class="wrapper-box">
	<div class="main-wrapper">
		<div id="container">
			<!--Left Part-->
			<div id="column-left">
				<div class="box">
					<div class="box-heading">
						Information
					</div>
					<div class="box-content">
						<ul class="list-item">
							<li>
								<%= link_to "About Us",about_us_path %>
							</li>
							<li>
								<%= link_to "Delivery Information",delivery_information_path %>
							</li>
							<li>
								<%= link_to "Privacy Policy",privacy_policy_path %>
							</li>
							<li>
								<%= link_to "Terms Conditions",terms_conditions_path %>
							</li>
							<li>
								<%= link_to "Contact Us",contact_us_path %>
							</li>
						</ul>
					</div>
				</div>

			</div>
			<!--Left End-->
			<!--Middle Part Start-->
			<div id="content">
				<!--Breadcrumb Part Start-->
				<div class="breadcrumb">
					<%= link_to "Home",root_path %> » <%= link_to "Delivery Information",delivery_information_path %>
				</div>
				<!--Breadcrumb Part End-->
				<ol>
					<li>
						<p align="left" style="margin-top: 0.19in; margin-bottom: 0.19in; line-height: 100%">
							<font face="Times New Roman, serif"><font size="5" style="font-size: 18pt"><b>DELIVERY
									OF PRODUCTS</b></font></font>
						</p>
						<ol type="i">
							<li>
								<p align="left" style="margin-top: 0.19in; margin-bottom: 0.19in; line-height: 100%">
									<font face="Times New Roman, serif"><font size="3" style="font-size: 12pt">Delivery
											of Product is made within 1 week from the date of official
											confirmation of order or redemption. (Subject to the place).</font></font>
								</p>
							<li>
								<p align="left" style="margin-top: 0.19in; margin-bottom: 0.19in; line-height: 100%">
									<font face="Times New Roman, serif"><font size="3" style="font-size: 12pt"><b>S&amp;N</b></font></font><font face="Times New Roman, serif"><font size="3" style="font-size: 12pt"> and their Agents are using a reliable courier services for the
											product delivery.</font></font>
								</p>
							<li>
								<p align="left" style="margin-top: 0.19in; margin-bottom: 0.19in; line-height: 100%">
									<font face="Times New Roman, serif"><font size="3" style="font-size: 12pt">Delivery
											charges will have to be paid by the customer at the time of
											purchasing/redeeming the product as per the customer's region. </font></font><font face="Times New Roman, serif"><font size="3" style="font-size: 12pt"><b>S&amp;N</b></font></font><font face="Times New Roman, serif"><font size="3" style="font-size: 12pt"> will not be responsible of all the local duties, custom taxes.</font></font>
								</p>
							<li>
								<p align="left" style="margin-top: 0.19in; margin-bottom: 0.19in; line-height: 100%">
									<font face="Times New Roman, serif"><font size="3" style="font-size: 12pt">Products
											that have been returned to </font></font><font face="Times New Roman, serif"><font size="3" style="font-size: 12pt"><b>S&amp;N</b></font></font><font face="Times New Roman, serif"><font size="3" style="font-size: 12pt"> due to customer's incorrect mailing address, telephone number or
											any other reason such as an absent customer etc will cost the
											customer delivery charges + Admin reshipping charges (vary from
											region to region) if the customer requests for a re-shipment of the
											product.</font></font>
								</p>
							<li>
								<p align="left" style="margin-top: 0.19in; margin-bottom: 0.19in; line-height: 100%">
									<font face="Times New Roman, serif"><font size="3" style="font-size: 12pt">Whether
											the customer wishes to get his product reshipped or not, his
											account will be deducted with the custom charges paid on his behalf
											by the courier for any reason that leads to the return of the
											shipment to the sender. If the customer's account doesn't
											sufficient balance, it will be credited with negative balance which
											will be replenished from any other financial transaction or
											commission earned by the customer.</font></font>
								</p>
							<li>
								<p align="left" style="margin-top: 0.19in; margin-bottom: 0.19in; line-height: 100%">
									<font face="Times New Roman, serif"><font size="3" style="font-size: 12pt">In
											case of unavoidable circumstances when </font></font><font face="Times New Roman, serif"><font size="3" style="font-size: 12pt"><b>S&amp;N</b></font></font><font face="Times New Roman, serif"><font size="3" style="font-size: 12pt"> is unable to deliver the product as shortage of product or product
											discontinuation, </font></font><font face="Times New Roman, serif"><font size="3" style="font-size: 12pt"><b>S&amp;N</b></font></font><font face="Times New Roman, serif"><font size="3" style="font-size: 12pt"> has right to replace the requested product with any of its existing
											products with same or higher value without any notice to customer.</font></font>
								</p>
							<li>
								<p align="left" style="margin-top: 0.19in; margin-bottom: 0.19in; line-height: 100%">
									<font face="Times New Roman, serif"><font size="3" style="font-size: 12pt">Exceptional
											cases where </font></font><font face="Times New Roman, serif"><font size="3" style="font-size: 12pt"><b>S&amp;N</b></font></font><font face="Times New Roman, serif"><font size="3" style="font-size: 12pt"> products cannot reach the destination due to severe or complex
											Customs rules and regulations, the customer will have to acquire
											the product themselves from the nearest territorial service centre
											or an authorized agent. </font></font><font face="Times New Roman, serif"><font size="3" style="font-size: 12pt"><b>S&amp;N</b></font></font><font face="Times New Roman, serif"><font size="3" style="font-size: 12pt"> will not be responsible for the traveling or any other expanses
											borne by the customer to acquire their product in that case.</font></font>
								</p>
						</ol>

				</ol>

			</div>
			<!--Middle Part End-->
			<div class="clear"></div>
		</div>
	</div>
</div>

app/views/home/index.html.erb
<div class="wrapper-box">
  <div class="main-wrapper">
    <!--Header Part End-->
    <div id="container">
      <div id="content">
        <!-- Nivo Slider Start -->
        <section class="slider-wrapper">
          <div id="slideshow" class="nivoSlider">
            <% dir_name="app/assets/images/slider_images" %>
            <% if File.exist?(dir_name) %>
                <% @slider_images=get_slider_images %>
                <% if @slider_images && @slider_images.count>0 %>
                    <% @slider_images.each do |slider_image| %>
                        <a class="nivo-imageLink" href="#"><%= image_tag("slider_images/#{slider_image}") %></a>
                    <% end %>
                <% else %>
                    <a class="nivo-imageLink" href="#"><img src="/assetslogo.png"/></a>
                <% end %>
            <% end %>
          </div>

        </section>
        <script type="text/javascript"><!--
        $('#slideshow').nivoSlider();
        /* $(document).ready(function() {

         $('#slideshow').nivoSlider();
         });*/
        --></script>
        <!-- Nivo Slider end -->
        <!-- Welcom Text Start-->
        <div class="welcome">Welcome to Polishop</div>
        <p><strong>Polishop</strong> Premium Responsive HTML Template. Polishop is a clean and Fully Responsive to use
          the
          template for every kind of eCommerce online shop. Great Looks on Desktops, Tablets and Mobiles. Well
          Documented.
          Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's
          standard dummy text ever since the 1500s, <a href="#">BUY THEME</a>.</p>
        <!-- Welcom Text End-->
        <%= render 'layouts/featured_products' %>
        <%= render 'layouts/products_tabs' %>
      </div>

    </div>
  </div>
</div>