config/routes.rb
Rails.application.routes.draw do

  root to: 'home#index'
  get 'admin/index'
  get 'admin/confirm_first_product_deliverd'
  post 'admin/admin_login'
  post 'admin/create'
  post 'admin/search_users_by_username'
  post '/admin/update_slider_images'
  post '/admin/search_admins_by_username'
  patch 'admin/reset_password'
  match '/admin_login', :to => 'admin#login', :via => 'get'
  match '/admin_signup', :to => 'admin#new', :via => 'get'
  match '/admin_signout', :to => 'admin#destroy', :via => 'get'
  match '/admin_index', :to => 'admin#index', :via => 'get'
  match '/admin/search_users', :to => 'admin#search_users', :via => 'get'
  match '/admin/reset_user_password', :to => 'admin#reset_user_password', :via => 'get'
  match '/admin_store_categories', :to => 'store#store_categories', :via => 'get'
  match '/admin_store_sub_categories', :to => 'store#sub_categories', :via => 'get'
  match '/admin_store_products', :to => 'store#products', :via => 'get'
  match '/admin_store_selected_product', :to => 'store#product', :via => 'get'
  match '/admin/choose_action', :to => 'admin#user_actions', :via => 'get'
  match '/admin/user_expenses', :to => 'admin#user_expenses', :via => 'get'
  match '/users_first_products', :to=> 'admin#users_first_products', :via => 'get'
  patch '/admin/generate_code'
  match '/admin/codes', :to => 'admin#codes', :via => 'get'
  match '/slider_images', :to => 'admin#slider_images', :via => 'get'
  match '/calculations', :to => 'admin#calculations', :via => 'get'
  patch '/admin/update_calculations'
  match '/admin_actions', :to => 'admin#admin_actions', :via => 'get'
  match '/search_admins', :to => 'admin#search_admins', :via => 'get'
  match '/edit_info', :to => 'admin#edit_info', :via => 'get'
  match '/update_sub_admin', :to => 'admin#update_sub_admin', :via => 'get'
  match '/update_super_admin', :to => 'admin#update_super_admin', :via => 'get'
  patch '/admin/update_sub_admin_info'
  patch '/admin/update_super_admin_info'
  patch '/admin/reset_super_admin_password'
  patch '/admin/reset_sub_admin_password'
  match '/all_sub_admins', :to => 'admin#all_sub_admins', :via => 'get'
  match '/view_sub_admin', :to => 'admin#view_sub_admin', :via => 'post'
  match '/admin/view_searched_user', :to => 'admin#view_searched_user', :via => 'post'
  match '/admin/edit_searched_user', :to => 'admin#edit_searched_user', :via => 'post'
  post 'admin/update_searched_user_info'
  match '/admin/update_governorates', :to => 'user#update_governorates', :via => 'get'
  match '/admin/update_regions', :to => 'user#update_regions', :via => 'get'

  match '/products_orders',:to=>'admin#confirm_products_order', :via => 'get'
  get 'admin/confirm_products_order_deliverd'

  match '/store_categories' , :to => 'application#store_categories', :via => 'get'
  match '/store_products', :to => 'application#products', :via => 'get'
  match '/store_selected_product', :to => 'application#product', :via => 'get'
  match '/store_sub_categories', :to => 'application#store_sub_categories', :via => 'get'

  get 'home/index'

  post 'place/create_country'
  post 'place/create_governorate'
  post 'place/create_region'
  match '/place', :to => 'place#index', :via => 'get'
  match '/add_country', :to => 'place#add_country', :via => 'get'
  match '/add_governorate', :to => 'place#add_governorate', :via => 'get'
  match '/add_region', :to => 'place#add_region', :via => 'get'
  get 'place/index'
  get 'place/add_country'
  get 'place/add_governorate'
  get 'place/add_region'
  get 'store/index'
  patch 'place/update_region'
  match '/countries', :to => 'place#countries', :via => 'get'
  match '/governorates', :to => 'place#governorates', :via => 'get'
  match '/regions', :to => 'place#regions', :via => 'get'
  match '/selected_region', :to => 'place#region', :via => 'get'
  patch 'place/update_country'
  patch 'place/update_governorate'
  match '/place/update_governorates', :to => 'user#update_governorates', :via => 'get'
  match '/place/update_regions', :to => 'user#update_regions', :via => 'get'

  match '/add_product_order', :to => 'product_order#add_product_order', :via => 'get'
  match '/add_product_order', :to => 'product_order#add_product_order_old_customer', :via => 'get'
  post 'product_order/create_product_order'
  post 'product_order/create_product_order_old_customer'
  match '/add_product_order', :to => 'product_order#add_product_order', :via => 'get'
  post 'product_order/create_product_order'
  match '/empty_cart', :to => 'product_order#empty_cart', :via => 'post'
  post 'product_order/empty_cart'
  match '/add_to_cart', :to => 'product_order#add_to_cart', :via => 'post'
  post 'product_order/add_to_cart'
  match '/remove_product_from_cart', :to => 'product_order#remove_product_from_cart', :via => 'get'
  get 'product_order/remove_product_from_cart'

  get 'profile/index'
  match '/profile', :to => 'profile#index', :via => 'get'
  match '/user_order', :to => 'profile#product_credit_order', :via => 'get'
  match '/generate_code', :to => 'profile#generate_code', :via => 'post'
  post 'profile/generate_code'
  match '/get_left', :to => 'profile#get_left', :via => 'get'
  match '/get_parent', :to => 'profile#get_parent', :via => 'get'
  match '/get_right', :to => 'profile#get_right', :via => 'get'
  get 'profile/get_left'
  get 'profile/get_parent'
  get 'profile/get_right'

  get 'session/new'
  post 'session/create'
  match '/signin', :to => 'session#new', :via => 'get'
  match '/signout', :to => 'session#destroy', :via => 'get'

  get 'store/add_category'
  get 'store/add_sub_category'
  get 'store/add_product'
  post 'store/create_category'
  post 'store/create_sub_category'
  post 'store/create_product'
  match '/store', :to => 'store#index', :via => 'get'
  match '/add_category', :to => 'store#add_category', :via => 'get'
  match '/add_sub_category', :to => 'store#add_sub_category', :via => 'get'
  match '/add_product', :to => 'store#add_product', :via => 'get'
  patch 'store/update_product'
  patch 'store/update_category_name'
  patch 'store/update_sub_category_name'
  match '/store/all_products', :to => 'store#all_products', :via => 'get'

  get 'user/show'
  get 'user/new'
  get 'user/edit_info'
  get 'user/index'
  get 'user/change_password'
  get 'user/show'
  post 'user/create'
  match '/create', :to=>'user#create',:via=>'post'
  match '/verify_email_create', :to=>'user#verify_email_create',:via=>'post'
  post 'user/index'
  patch 'user/update_user_info'
  patch 'user/update_password'
  match '/signUp', :to => 'user#sign_up', :via => 'get'
  match '/edit_profile', :to => 'user#edit_info', :via => 'get'
  match '/change_password', :to => 'user#change_password', :via => 'get'
  match '/verify_email', :to => 'user#verify_email_create', :via => 'post'
  match '/verify_email', :to => 'user#verify_email', :via => 'get'
  match '/forgetPassword', :to => 'user#forget_password', :via => 'get'
  match '/send_new_password', :to => 'user#send_new_password', :via => 'post'
  match '/expenses', :to => 'user#expenses', :via => 'get'
  match '/first_product', :to => 'user#first_product', :via => 'get'
  get '/user/select_first_product'
  match '/update_governorates', :to => 'user#update_governorates', :via => 'get'
  match '/update_regions', :to => 'user#update_regions', :via => 'get'
  match '/user/update_governorates', :to => 'user#update_governorates', :via => 'get'
  match '/user/update_regions', :to => 'user#update_regions', :via => 'get'

  get '/about_us',:to => 'home#about_us', :via => 'get'
  get '/contact_us',:to => 'home#contact_us', :via => 'get'
  get '/delivery_information',:to => 'home#delivery_information', :via => 'get'
  get '/terms_conditions',:to => 'home#terms_conditions', :via => 'get'
  get '/privacy_policy',:to => 'home#privacy_policy', :via => 'get'

  match '*not_found', to: 'errors#error_404', via: :all

end

app/helpers/store_helper.rb
module StoreHelper
def get_user_info_by_sale(sale)
    expense=Expense.find_by_sale_id(sale.id)
    if expense
      user_info=UserInfo.find_by_user_id(expense.user_id)
    return user_info
    end
  end

  def get_product_has_sale_from_sale(sale)
    product_has_sales=ProductHasSale.where("sale_id=?",sale.id)
    if product_has_sales
    return product_has_sales
    end
  end

  def get_product_by_product_sale(product_has_sale)
    product=Product.find(product_has_sale.product_id)
    if product
    return product
    end
  end

  def get_total_of_sale(sale)
    product_has_sales=ProductHasSale.where("sale_id=?",sale.id)
    total=0
    if product_has_sales
      product_has_sales.each  do|ps|
        total+=(ps.price*ps.amount)
      end
    return total
    end
  end
end

app/views/store/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(object.errors.count, "error") %>
      prohibited this <%= object.class.to_s.underscore.humanize.downcase %>
      from being saved:
    </h2>
    <p>There were problems with the following fields:</p>
    <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
  
<% end %>

app/views/store/add_category.html.erb
<center>
  <% if @category && @category.errors.full_messages.any? %>
      <div id="error_explanation">
        <% @category.errors.full_messages.each do |error_message| %>
            <h2><%= error_message if @category.errors.full_messages.first == error_message %></h2>
        <% end %>
      </div>
  <% end %>
  <h1>Add category</h1>
  <%= form_for @category, url: {action: "create_category"} do |f| %>
      <% if @category.errors.full_messages.any? %>
          <% @category.errors.full_messages.each do |error_message| %>
              <%= error_message if @category.errors.full_messages.first == error_message %>
          <% end %>
      <% end %>
      <table>
        <tr>
          <td><h3>Category name </h3></td>
          <td> : <%= f.text_field :name %>
          </td>
        </tr>
        <tr>
          <td><br/></td>
        </tr>
        <tr>
          <td>Choose an image </h3></td>
          <td>
            : <%= f.file_field :category_image, accept: 'image/png,image/gif,image/jpeg,image/jpg,image/PNG,image/GIF,image/JPEG,image/JPG' %> </td>
        </tr>
        <tr>
          <td><br/></td>
        </tr>
        <tr>
          <td></td>
          <td> <%= f.submit "Create Category", :class => "button" %> </td>
        </tr>
      </table>


  <% end %>
</center>

app/views/store/add_product.html.erb
<center>
  <% flash.each do |key, value| %>
      <% id= (key=="success") ? "success_messages" : "error_explanation" %>
      <div id=<%= id %>>
        <h2><%= value %></h2>
      </div>
  <% end %>
  <% if @product && @product.errors.full_messages.any? %>
      <div id="error_explanation">
        <% @product.errors.full_messages.each do |error_message| %>
            <h2><%= error_message if @product.errors.full_messages.first == error_message %></h2>
        <% end %>
      </div>
  <% end %>
  <h1>Add Product</h1>
  <%= form_for @product, url: {action: "create_product"} do |f| %>
      <table>
        <tr>
          <td><h3>Product name </h3></td>
          <td>: <%= f.text_field :name %> </td>
        </tr>
        <tr>
          <td><h3>Sub_category </h3></td>
          <td> : <%= f.grouped_collection_select :sub_category_id, Category.order(:name),
                                                 :sub_categories, :name, :id, :name %> </td>
        </tr>
        <tr>
          <td><h3>Price </h3></td>
          <td> :  <%= f.number_field :price, in: 1.0..1000000.0 %> </td>
        </tr>
        <tr>
          <td><h3>Description </h3></td>
          <td> : <%= f.text_area :description, :cols => "30", :rows => "5" %> </td>
        </tr>
        <tr>
          <td><h3>Quantity </h3></td>
          <td> : <%= f.number_field :quantity, in: 0.0..1000000.0 %> </td>
        </tr>
        <tr>
          <td><h3>Real price </h3></td>
          <td>: <%= f.number_field :real_price, in: 1.0..1000000.0 %> </td>
        </tr>
        <tr>
          <td><h3>Offer </h3></td>
          <td> : <%= f.number_field :offer, in: 1.0..50.0 %> </td>
        </tr>
        <tr>
          <td><h3>Offer expired date</h3></td>
          <td> : <%= f.date_field :offer_expired_date, :value => Time.now.strftime('%Y-%m-%d') %>  </td>
        </tr>
        <tr>
          <td><h3>Is best seller </h3></td>
          <td> : <%= f.check_box :is_best_seller %>  </td>
        </tr>
        <tr>
          <td><h3>Is featured </h3></td>
          <td> : <%= f.check_box :is_featured %>  </td>
        </tr>
        <tr>
          <td><h3>Choose an image</h3></td>
          <td>: <%= f.file_field :datafile1, accept: 'image/png,image/gif,image/jpeg,image/jpg,image/PNG,image/GIF,image/JPEG,image/JPG' %> </td>
        </tr>
        <tr>
          <td><h3>Choose an image</h3></td>
          <td>
            : <%= f.file_field :datafile2, accept: 'image/png,image/gif,image/jpeg,image/jpg,image/PNG,image/GIF,image/JPEG,image/JPG' %> </td>
        </tr>
        <tr>
          <td><h3>Choose an image</h3></td>
          <td>
            : <%= f.file_field :datafile3, accept: 'image/png,image/gif,image/jpeg,image/jpg,image/PNG,image/GIF,image/JPEG,image/JPG' %> </td>
        </tr>
        <tr>
          <td></td>
          <td>
            <br/> <%= f.submit "Create Product", :class => "button" %>
        </tr>
      </table>


  <% end %>
</center>

app/views/store/add_sub_category.html.erb
<center>
  <% flash.each do |key, value| %>
      <% id= (key=="success") ? "success_messages" : "error_explanation" %>
      <div id=<%= id %>>
        <h2><%= value %></h2>
      </div>
  <% end %>
  <% if @sub_category && @sub_category.errors.full_messages.any? %>
      <div id="error_explanation">
        <% @sub_category.errors.full_messages.each do |error_message| %>
            <h2><%= error_message if @sub_category.errors.full_messages.first == error_message %></h2>
        <% end %>
      </div>
  <% end %>
  <h1>Add Sub category</h1>
  <%= form_for @sub_category, url: {action: "create_sub_category"} do |f| %>
      <table>
        <tr>
          <td><h3>Sub category name </h3></td>
          <td> : <%= f.text_field :name %> </td>
        </tr>
        <tr>
          <td><br/></td>
        </tr>
        <tr>
          <td><h3>Category name </h3></td>
          <td>
            :<%= f.collection_select :category_id, Category.order(:name), :id, :name %>

          </td>
        </tr>
        <tr>
          <td><br/></td>
        </tr>
        <tr>
          <td><h3>Choose an image </h3></td>
          <td>
            : <%= f.file_field :sub_category_image, accept: 'image/png,image/gif,image/jpeg,image/jpg,image/PNG,image/GIF,image/JPEG,image/JPG' %> </td>
        </tr>
      </table>
      <br/>
      <%= f.submit "Create sub Category", :class => "button" %>

  <% end %>
</center>

app/views/store/all_products.html.erb
<div align="center">
  <%= link_to  "Add a new product " , add_product_path,:class=>"button" %>
  <br/><br/>
  <h1>All products</h1>
  <style type="text/css">
      table.myTable {
          border-collapse: collapse;
      }

      table.myTable td, table.myTable th {
          border: 1px solid black;
          padding: 10px;
          font-size: 18px;
          text-align: center;
      }
  </style>
  <table class="myTable">
    <tr>
      <th>Product name</th>
      <th> Quantity</th>
      <th> Price</th>
      <th> Real price</th>
      <th> Edit Product</th>
    </tr>
    <% @all_products.each do |product| %>
        <tr>
          <td><%= product.name %></td>
          <td><%= product.quantity %></td>
          <td><%= product.price %></td>
          <td><%= product.real_price %></td>
          <td>
              <%= link_to  "Edit product" ,"/admin_store_selected_product?product_id=#{product.id}" ,:class=>"button" %>
          </td>
        </tr>
    <% end %>
  </table>
</div>

app/views/store/index.html.erb
<center>
	<% flash.each do |key, value| %>
	<% id= (key=="success") ? "success_messages" : "error_explanation" %>
	<div id=<%= id %>>
		<h2><%= value %></h2>
	</div>
	<% end %>
</center>
<h1>Store</h1>
<div class="backs" >
  <a href=<%= add_category_path %>>
    <div class="button_bases b1_skewed_slide_in">
      <div>Add category</div>
      <div></div>
      <div>Add category</div>
    </div>
  </a>
</div>
<div class="backs" >
  <a href=<%= add_sub_category_path %>>
    <div class="button_bases b1_skewed_slide_in">
      <div>Add sub category</div>
      <div></div>
      <div>Add sub category</div>
    </div>
  </a>
</div>
<div class="backs" >
  <a href=<%= add_product_path %>>
    <div class="button_bases b1_skewed_slide_in">
      <div>Add product</div>
      <div></div>
      <div>Add product</div>
    </div>
  </a>
</div>
<div class="backs" >
  <a href=<%= admin_store_categories_path %>>
    <div class="button_bases b1_skewed_slide_in">
      <div>Edit Store</div>
      <div></div>
      <div>Edit Store</div>
    </div>
  </a>
</div>

app/views/store/product.html.erb
<center>
  <% flash.each do |key, value| %>
      <% id= (key=="success") ? "success_messages" : "error_explanation" %>
      <div id=<%= id %>>
        <h2><%= value %></h2>
      </div>
  <% end %>
  <% if @selected_product && @selected_product.errors.full_messages.any? %>
      <div id="error_explanation">
        <% @selected_product.errors.full_messages.each do |error_message| %>
            <h2><%= error_message if @selected_product.errors.full_messages.first == error_message %></h2>
        <% end %>
      </div>
  <% end %>
  <h1>Update Product</h1>
  <%= form_for @selected_product, url: {action: "update_product"} do |f| %>
      <table>
        <tr>
          <td width="120px"><h3>Product name </h3></td>
          <td>: <%= f.text_field :name %> </td>
          </td>
        </tr>
        <tr>
          <td><h3>Sub_category </h3></td>
          <td> : <%= f.grouped_collection_select :sub_category_id, Category.order(:name),
                                                 :sub_categories, :name, :id, :name, include_blank: true %> </td>
          </td>
        </tr>
        <tr>
          <td><h3>Price </h3></td>
          <td> :  <%= f.number_field :price, in: 1.0..1000000.0 %> </td>
          </td>
        </tr>
        <tr>
          <td><h3>Description </h3></td>
          <td> : <%= f.text_area :description, :cols => "30", :rows => "5" %> </td>
          </td>
        </tr>
        <tr>
          <td><h3>Quantity </h3></td>
          <td> : <%= f.number_field :quantity, in: 0.0..1000000.0 %> </td>
          </td>
        </tr>
        <tr>
          <td><h3>Real price </h3></td>
          <td>: <%= f.number_field :real_price, in: 1.0..1000000.0 %> </td>
          </td>
        </tr>
        <tr>
          <td><h3>Offer </h3></td>
          <td> : <%= f.number_field :offer, in: 1.0..50.0 %> </td>
          </td>
        </tr>
        <tr>
          <td><h3>Offer expired date </h3></td>
          <td> : <%= f.date_field :offer_expired_date %> </span> </h3></td>
        </tr>
        <tr>
          <td><h3>Is best seller </h3></td>
          <td> : <%= f.check_box :is_best_seller %>  </td>
        </tr>
        <tr>
          <td><h3>Is featured </h3></td>
          <td> : <%= f.check_box :is_featured %>  </td>
        </tr>

        <% if @selected_product_images && !@selected_product_images.empty? %>
            <br/>
            <br/>
            <% @selected_product_images.each do |image| %>
                <tr>
                  <td><h3>Product image </h3></td>
                  <% if image.include? '1' %>
                      <td> : <%= image_tag("data/products/#{@selected_product.id}/#{image}", :size => "300x200") %>
                        <h3>Select another File
                          : <%= f.file_field :datafile1, accept: 'image/png,image/gif,image/jpeg,image/jpg,image/PNG,image/GIF,image/JPEG,image/JPG' %>
                          <h3><br/>
                      </td>
                  <% elsif image.include? '2.jpg' %>
                      <td> : <%= image_tag("data/products/#{@selected_product.id}/#{image}", :size => "300x200") %>
                        <h3>Select another File
                          : <%= f.file_field :datafile2, accept: 'image/png,image/gif,image/jpeg,image/jpg,image/PNG,image/GIF,image/JPEG,image/JPG' %>
                          <h3><br/>
                      </td>
                  <% elsif image.include? '3.jpg' %>
                      <td> : <%= image_tag("data/products/#{@selected_product.id}/#{image}", :size => "300x200") %>
                        <h3>Select another File
                          : <%= f.file_field :datafile3, accept: 'image/png,image/gif,image/jpeg,image/jpg,image/PNG,image/GIF,image/JPEG,image/JPG' %>
                          <h3><br/>
                      </td>
                  <% end %>
                </tr>

            <% end %>
            <% if @selected_product_images.count < 3 %>
                <% allowed_upload= 3 - @selected_product_images.count %>
                <% index= @selected_product_images.count+1 %>
                <% for i in 1..allowed_upload %>
                    <% if index==2 %>
                        <tr>
                          <td><h3>Select File </h3></td>
                          <td>: <%= f.file_field :datafile2, accept: 'image/png,image/gif,image/jpeg,image/jpg,image/PNG,image/GIF,image/JPEG,image/JPG' %> </td>
                        </tr>
                    <% else %>
                        <td><h3>Select File </h3></td>
                        <td>: <%= f.file_field :datafile3, accept: 'image/png,image/gif,image/jpeg,image/jpg,image/PNG,image/GIF,image/JPEG,image/JPG' %> </td>
                    <% end %>

                <% end %>
            <% end %>
        <% else %>
            <table>
              <tr>
                <td width="120px"><h3>Select File </h3></td>
                <td>: <%= f.file_field :datafile1, accept: 'image/png,image/gif,image/jpeg,image/jpg,image/PNG,image/GIF,image/JPEG,image/JPG' %> </td>
              </tr>
              <tr>
                <td><h3>Select File </h3></td>
                <td>
                  : <%= f.file_field :datafile2, accept: 'image/png,image/gif,image/jpeg,image/jpg,image/PNG,image/GIF,image/JPEG,image/JPG' %> </td>
              </tr>
              <tr>
                <td><h3>Select File </h3></td>
                <td>
                  : <%= f.file_field :datafile3, accept: 'image/png,image/gif,image/jpeg,image/jpg,image/PNG,image/GIF,image/JPEG,image/JPG' %> </td>
              </tr>
            </table>
        <% end %>
      </table>
      <br/>
      <%= f.submit "Update Product", :class => "button" %>
  <% end %>
</center>

app/views/store/products.html.erb
<center>
  <% flash.each do |key, value| %>
      <% id= (key=="success") ? "success_messages" : "error_explanation" %>
      <div id=<%= id %>>
        <h2><%= value %></h2>
      </div>
  <% end %>
  <% if @selected_sub_category && @selected_sub_category.errors.full_messages.any? %>
      <div id="error_explanation">
        <% @selected_sub_category.errors.full_messages.each do |error_message| %>
            <h2><%= error_message if @selected_sub_category.errors.full_messages.first == error_message %></h2>
        <% end %>
      </div>
  <% end %>
  <h1>Update <%= @selected_sub_category.name %></h1>
  <%= form_for @selected_sub_category, url: {action: "update_sub_category_name"} do |f| %>
      <table>
        <tr>
          <td><h3>Sub category name </h3></td>
          <td> : <%= f.text_field :name %> </td>
        </tr>
        <tr>
          <td><h3>Category name </h3></td>
          <td>
            :<%= f.collection_select :category_id, Category.order(:name), :id, :name, include_blank: true %>

          </td>
        </tr>
        <tr>
          <% if @sub_category_images %>
              <td><h3>Sub_category image </h3></td>
              <td>
                : <%= image_tag("data/sub_categories/#{@selected_sub_category.id}/#{@sub_category_images[0]}", :size => "250x200") %>
                <h3>Change image<%= f.file_field :sub_category_image %>
                  <h3>
              </td>
          <% else %>
              <td><h3>Choose an image </h3></td>
              <td> : <%= f.file_field :sub_category_image %> </td>
          <% end %>

        </tr>
      </table>
      <br/>
      <%= f.submit "Update Subcategoy ", :class => "button" %>
      <br/><br/>
  <% end %>
</center>
<% if @products.count>0 %>
    <h1> Products of <%= @selected_sub_category.name %> </h1>
    <% @products.each do |product| %>
        <div class="backs">
          <%= link_to "/admin_store_selected_product?product_id=#{product.id}", {:controller => "store", :action => "product", :product_id => product.id} do %>
              <div class="button_bases b1_skewed_slide_in">
                <div><%= product.name %></div>
                <div></div>
                <div><%= product.name %></div>
              </div>
          <% end %>
        </div>
    <% end %>
    <!--Pagination Part Start-->
    <div class="flickr_pagination">
      <%= will_paginate @products %>
    </div>
    <!--Pagination Part End-->
<% else %>

    <h1>No Products for <%= @selected_sub_category.name %> </h1>
<% end %>

app/views/store/store_categories.html.erb
<center>
  <% flash.each do |key, value| %>
      <% id= (key=="success") ? "success_messages" : "error_explanation" %>
      <div id=<%= id %>>
        <h2><%= value %></h2>
      </div>
  <% end %>
</center>
<h1>Store Categories </h1>

<% @categories.each do |category| %>

    <div class="backs">
      <%= link_to "admin_store_sub_categories?category_id=#{category.id}", {:controller => "store", :action => "sub_categories", :category_id => category.id} do %>
          <div class="button_bases b1_skewed_slide_in">
            <div><%= category.name %></div>
            <div></div>
            <div><%= category.name %></div>
          </div>
      <% end %>
    </div>

<% end %>
<!--Pagination Part Start-->
<div class="flickr_pagination">
  <%= will_paginate @categories %>
</div>
<!--Pagination Part End-->

app/views/store/sub_categories.html.erb
<center>
  <% flash.each do |key, value| %>
      <% id= (key=="success") ? "success_messages" : "error_explanation" %>
      <div id=<%= id %>>
        <h2><%= value %></h2>
      </div>
  <% end %>
  <% if @selected_category && @selected_category.errors.full_messages.any? %>
      <div id="error_explanation">
        <% @selected_category.errors.full_messages.each do |error_message| %>
            <h2><%= error_message if @selected_category.errors.full_messages.first == error_message %></h2>
        <% end %>
      </div>
  <% end %>
  <h1><%= @to_be_updated_category.name %></h1>
  <%= form_for @selected_category, url: {action: "update_category_name"} do |f| %>
      <table>
        <tr>
          <td><h3>Category name </h3></td>
          <td> : <%= f.text_field :name %>
          </td>
        </tr>
        <tr>
          <td><br/></td>
        </tr>
        <tr>
          <% if @category_images %>
              <td><h3>Category image </h3></td>
              <td>
                : <%= image_tag("data/categories/#{@selected_category.id}/#{@category_images[0]}", :size => "250x200") %>
                <h3>Change image<%= f.file_field :category_image %>
                  <h3>
              </td>
          <% else %>
              <td><h3>Choose an image </h3></td>
              <td> : <%= f.file_field :category_image %> </td>
          <% end %>

        </tr>
        <tr>
          <td><br/></td>
        </tr>
        <tr>
          <td></td>
          <td> &nbsp;&nbsp;  <%= f.submit "Update Category", :class => "button" %></td>
        </tr>
      </table>


  <% end %>
  <br/>
</center>
<% if @sub_categories.count>0 %>

    <h1>Select sub category</h1>
    <% @sub_categories.each do |sub_category| %>
        <div class="backs">
          <%= link_to "/admin_store_products?sub_category_id=#{sub_category.id}", {:controller => "store", :action => "products", :sub_category_id => sub_category.id} do %>
              <div class="button_bases b1_skewed_slide_in">
                <div><%= sub_category.name %></div>
                <div></div>
                <div><%= sub_category.name %></div>
              </div>
          <% end %>
        </div>

    <% end %>
    <!--Pagination Part Start-->
    <div class="flickr_pagination">
      <%= will_paginate @sub_categories %>
    </div>
    <!--Pagination Part End-->
<% else %>
    <h1>No subcategories found</h1>
<% end %>