config/routes.rb
Rails.application.routes.draw do

  root to: 'home#index'
  get 'admin/index'
  get 'admin/confirm_first_product_deliverd'
  post 'admin/admin_login'
  post 'admin/create'
  post 'admin/search_users_by_username'
  post '/admin/update_slider_images'
  post '/admin/search_admins_by_username'
  patch 'admin/reset_password'
  match '/admin_login', :to => 'admin#login', :via => 'get'
  match '/admin_signup', :to => 'admin#new', :via => 'get'
  match '/admin_signout', :to => 'admin#destroy', :via => 'get'
  match '/admin_index', :to => 'admin#index', :via => 'get'
  match '/admin/search_users', :to => 'admin#search_users', :via => 'get'
  match '/admin/reset_user_password', :to => 'admin#reset_user_password', :via => 'get'
  match '/admin_store_categories', :to => 'store#store_categories', :via => 'get'
  match '/admin_store_sub_categories', :to => 'store#sub_categories', :via => 'get'
  match '/admin_store_products', :to => 'store#products', :via => 'get'
  match '/admin_store_selected_product', :to => 'store#product', :via => 'get'
  match '/admin/choose_action', :to => 'admin#user_actions', :via => 'get'
  match '/admin/user_expenses', :to => 'admin#user_expenses', :via => 'get'
  match '/users_first_products', :to=> 'admin#users_first_products', :via => 'get'
  patch '/admin/generate_code'
  match '/admin/codes', :to => 'admin#codes', :via => 'get'
  match '/slider_images', :to => 'admin#slider_images', :via => 'get'
  match '/calculations', :to => 'admin#calculations', :via => 'get'
  patch '/admin/update_calculations'
  match '/admin_actions', :to => 'admin#admin_actions', :via => 'get'
  match '/search_admins', :to => 'admin#search_admins', :via => 'get'
  match '/edit_info', :to => 'admin#edit_info', :via => 'get'
  match '/update_sub_admin', :to => 'admin#update_sub_admin', :via => 'get'
  match '/update_super_admin', :to => 'admin#update_super_admin', :via => 'get'
  patch '/admin/update_sub_admin_info'
  patch '/admin/update_super_admin_info'
  patch '/admin/reset_super_admin_password'
  patch '/admin/reset_sub_admin_password'
  match '/all_sub_admins', :to => 'admin#all_sub_admins', :via => 'get'
  match '/view_sub_admin', :to => 'admin#view_sub_admin', :via => 'post'
  match '/admin/view_searched_user', :to => 'admin#view_searched_user', :via => 'post'
  match '/admin/edit_searched_user', :to => 'admin#edit_searched_user', :via => 'post'
  post 'admin/update_searched_user_info'
  match '/admin/update_governorates', :to => 'user#update_governorates', :via => 'get'
  match '/admin/update_regions', :to => 'user#update_regions', :via => 'get'

  match '/products_orders',:to=>'admin#confirm_products_order', :via => 'get'
  get 'admin/confirm_products_order_deliverd'

  match '/store_categories' , :to => 'application#store_categories', :via => 'get'
  match '/store_products', :to => 'application#products', :via => 'get'
  match '/store_selected_product', :to => 'application#product', :via => 'get'
  match '/store_sub_categories', :to => 'application#store_sub_categories', :via => 'get'

  get 'home/index'

  post 'place/create_country'
  post 'place/create_governorate'
  post 'place/create_region'
  match '/place', :to => 'place#index', :via => 'get'
  match '/add_country', :to => 'place#add_country', :via => 'get'
  match '/add_governorate', :to => 'place#add_governorate', :via => 'get'
  match '/add_region', :to => 'place#add_region', :via => 'get'
  get 'place/index'
  get 'place/add_country'
  get 'place/add_governorate'
  get 'place/add_region'
  get 'store/index'
  patch 'place/update_region'
  match '/countries', :to => 'place#countries', :via => 'get'
  match '/governorates', :to => 'place#governorates', :via => 'get'
  match '/regions', :to => 'place#regions', :via => 'get'
  match '/selected_region', :to => 'place#region', :via => 'get'
  patch 'place/update_country'
  patch 'place/update_governorate'
  match '/place/update_governorates', :to => 'user#update_governorates', :via => 'get'
  match '/place/update_regions', :to => 'user#update_regions', :via => 'get'

  match '/add_product_order', :to => 'product_order#add_product_order', :via => 'get'
  match '/add_product_order', :to => 'product_order#add_product_order_old_customer', :via => 'get'
  post 'product_order/create_product_order'
  post 'product_order/create_product_order_old_customer'
  match '/add_product_order', :to => 'product_order#add_product_order', :via => 'get'
  post 'product_order/create_product_order'
  match '/empty_cart', :to => 'product_order#empty_cart', :via => 'post'
  post 'product_order/empty_cart'
  match '/add_to_cart', :to => 'product_order#add_to_cart', :via => 'post'
  post 'product_order/add_to_cart'
  match '/remove_product_from_cart', :to => 'product_order#remove_product_from_cart', :via => 'get'
  get 'product_order/remove_product_from_cart'

  get 'profile/index'
  match '/profile', :to => 'profile#index', :via => 'get'
  match '/user_order', :to => 'profile#product_credit_order', :via => 'get'
  match '/generate_code', :to => 'profile#generate_code', :via => 'post'
  post 'profile/generate_code'
  match '/get_left', :to => 'profile#get_left', :via => 'get'
  match '/get_parent', :to => 'profile#get_parent', :via => 'get'
  match '/get_right', :to => 'profile#get_right', :via => 'get'
  get 'profile/get_left'
  get 'profile/get_parent'
  get 'profile/get_right'

  get 'session/new'
  post 'session/create'
  match '/signin', :to => 'session#new', :via => 'get'
  match '/signout', :to => 'session#destroy', :via => 'get'

  get 'store/add_category'
  get 'store/add_sub_category'
  get 'store/add_product'
  post 'store/create_category'
  post 'store/create_sub_category'
  post 'store/create_product'
  match '/store', :to => 'store#index', :via => 'get'
  match '/add_category', :to => 'store#add_category', :via => 'get'
  match '/add_sub_category', :to => 'store#add_sub_category', :via => 'get'
  match '/add_product', :to => 'store#add_product', :via => 'get'
  patch 'store/update_product'
  patch 'store/update_category_name'
  patch 'store/update_sub_category_name'
  match '/store/all_products', :to => 'store#all_products', :via => 'get'

  get 'user/show'
  get 'user/new'
  get 'user/edit_info'
  get 'user/index'
  get 'user/change_password'
  get 'user/show'
  post 'user/create'
  match '/create', :to=>'user#create',:via=>'post'
  match '/verify_email_create', :to=>'user#verify_email_create',:via=>'post'
  post 'user/index'
  patch 'user/update_user_info'
  patch 'user/update_password'
  match '/signUp', :to => 'user#sign_up', :via => 'get'
  match '/edit_profile', :to => 'user#edit_info', :via => 'get'
  match '/change_password', :to => 'user#change_password', :via => 'get'
  match '/verify_email', :to => 'user#verify_email_create', :via => 'post'
  match '/verify_email', :to => 'user#verify_email', :via => 'get'
  match '/forgetPassword', :to => 'user#forget_password', :via => 'get'
  match '/send_new_password', :to => 'user#send_new_password', :via => 'post'
  match '/expenses', :to => 'user#expenses', :via => 'get'
  match '/first_product', :to => 'user#first_product', :via => 'get'
  get '/user/select_first_product'
  match '/update_governorates', :to => 'user#update_governorates', :via => 'get'
  match '/update_regions', :to => 'user#update_regions', :via => 'get'
  match '/user/update_governorates', :to => 'user#update_governorates', :via => 'get'
  match '/user/update_regions', :to => 'user#update_regions', :via => 'get'

  get '/about_us',:to => 'home#about_us', :via => 'get'
  get '/contact_us',:to => 'home#contact_us', :via => 'get'
  get '/delivery_information',:to => 'home#delivery_information', :via => 'get'
  get '/terms_conditions',:to => 'home#terms_conditions', :via => 'get'
  get '/privacy_policy',:to => 'home#privacy_policy', :via => 'get'

  match '*not_found', to: 'errors#error_404', via: :all

end

app/models/sale.rb
class Sale < ActiveRecord::Base
  belongs_to :customer
  has_many :products ,:through=> :product_has_sale
  has_one :expense
  validates :date, :presence => true
  
end

app/views/layouts/_brands.html.erb
<!-- Carousel Start-->
<section id="carousel">
  <ul class="jcarousel-skin-opencart">
    <li><a href="#"><img src="image/product/brand_logo.jpg" alt="brand_logo" title="brand_logo" /></a></li>
    <li><a href="#"><img src="image/product/brand_logo.jpg" alt="brand_logo" title="brand_logo" /></a></li>
    <li><a href="#"><img src="image/product/brand_logo.jpg" alt="brand_logo" title="brand_logo" /></a></li>
    <li><a href="#"><img src="image/product/brand_logo.jpg" alt="brand_logo" title="brand_logo" /></a></li>
    <li><a href="#"><img src="image/product/brand_logo.jpg" alt="brand_logo" title="brand_logo" /></a></li>
    <li><a href="#"><img src="image/product/brand_logo.jpg" alt="brand_logo" title="brand_logo" /></a></li>
  </ul>
</section>
<!-- Carousel End-->

app/views/layouts/_cart.html.erb
<section id="cart">
	<% get_total_price_and_count_of_product_in_session%>
	<div class="heading">
		<h4><img width="32" height="32" alt="" src="/assetscart-bg.png"></h4>
		<a><span id="cart-total"><%= @total_count_of_product %> item(s) - L.E <%= @total_price_of_product %></span></a>

	</div>
	<div class="content">
		<div class="mini-cart-info">
			<table>
				<tbody>
					<%if session[:product_ids]%>
					<% for p in 0...session[:product_ids].length %>
					<tr>
						<% product_from_session=get_product_from_session(p)%>
						<% puts"#{product_from_session.id}"%>
						<% if File.exist?("app/assets/images/data/#{product_from_session.id}") %>
						<% selected_product_image=get_product_images(product_from_session.id)%>

						<td class="image"> <%= link_to image_tag("data/#{product_from_session.id}/#{selected_product_image[0]}", :size => "47x47"),
						{:controller => "application", :action => "product", :product_id => product_from_session.id} %></td>
						<% else %>
						<td class="image"><%= link_to image_tag("/assets/logo.png", :size => "47x47"),
						{:controller => "application", :action => "product", :product_id => product_from_session.id} %></td>
						<% end %>
						<td class="name"><%= product_from_session.name %></td>
						<td class="quantity">x &nbsp;<%= get_product_count_from_session(p) %></td>
						<% check_offer=(product_from_session.offer && product_from_session.offer>0 )%>

						<% if check_offer %>
						<td class="total">L.E <%= product_from_session.price- (product_from_session.price* (product_from_session.offer / 100)) %></td>
						<%else%>
						<td class="total">L.E <%= product_from_session.price %></td>
						<%end%>
						<td class="remove"><%= link_to image_tag("/assets/remove-small.png"), {:controller => "product_order", :action => "remove_product_from_cart", :product_index => p,:remote=>true} %></td>
					</tr>
					<% end %>
					<% end %>
				</tbody>
			</table>
		</div>
		<div class="mini-cart-total">
			<% if session[:product_ids] &&
			!session[:product_ids].empty? %>
			<table>
				<tbody>
					<tr>
						<td class="right"><b>Total:</b></td>
						<td class="right">L.E <%= @total_price_of_product %></td>
					</tr>
				</tbody>
			</table>
		</div>
		<div class="checkout">
			<%= form_tag  'empty_cart',:remote=>true do-%>
			<%= submit_tag 'Empty cart' ,:class=>'button',data: { confirm: "Are you sure ?" }%>
			<%end-%>
			<% if user_is_signed_in? %>
			<%= link_to "Checkout", user_order_path, :class => 'button' %>
			<%else%>
			<%= link_to "Checkout", add_product_order_path, :class => 'button' %>
			<%end%>

		</div>
		<% else %>
		<h1>Empty Cart</h1>
		<% end %>
	</div>
</section>

app/views/layouts/_featured_products.html.erb
<!-- Featured Product Start-->
<section class="box">
  <div class="box-heading">Featured</div>
  <div class="box-content">
    <div class="box-product">
      <div class="flexslider featured_carousel">
        <% featued_products=get_featured_products %>
        <% if featued_products && !featued_products.empty? %>
            <ul class="slides">
              <% featued_products.each do |product| %>
                  <li>
                    <div class="slide-inner">
                      <div class="image">
                        <% if File.exist?("app/assets/images/data/products/#{product.id}") %>
                            <% selected_product_image=get_product_images(product.id) %>
                            <%= link_to image_tag("data/products/#{product.id}/#{selected_product_image[0]}"), {:controller => "application", :action => "product", :product_id => product.id} %>

                        <% else %>
                            <%= link_to image_tag("/assets/logo.png"), {:controller => "application", :action => "product", :product_id => product.id} %>
                        <% end %>
                      </div>
                      <div class="name">
                        <b> <%= link_to product.name, {:controller => "application", :action => "product", :product_id => product.id} %></b>
                      </div>
                      <% if product.offer &&product.offer>0 %>
                          <% new_price=product.price-(product.price* (product.offer / 100)) %>
                          <div class="price">
                            <span class="price-old"><%= product.price %></span>
                            <span class="price-new"><%= new_price %> $</span>
                            <br/>
                          </div>
                      <% else %>
                          <div class="price">
                            <span class="price-new"><%= product.price %> $</span>
                            <br/>
                          </div>
                      <% end %>
                      <div class="cart">
                        <%= form_tag 'add_to_cart', :remote => true do -%>
                            <%= hidden_field_tag "product_to_cart_id", product.id %>
                            <%= submit_tag 'Add To Cart', :class => 'button' %>
                        <% end -%>
                      </div>
                      <div class="clear"></div>
                    </div>
                  </li>
              <% end %>

            </ul>
        <% end %>

      </div>
    </div>
  </div>
</section>
<script type="text/javascript">
    (function () {
        // store the slider in a local variable
        var $window = $(window),
                flexslider;

        // tiny helper function to add breakpoints
        function getGridSize() {
            return (window.innerWidth < 320) ? 1 :
                    (window.innerWidth < 600) ? 2 :
                            (window.innerWidth < 800) ? 3 :
                                    (window.innerWidth < 900) ? 4 : 5;
        }

        $window.load(function () {
            $('#content .featured_carousel').flexslider({
                animation: "slide",
                animationLoop: false,
                slideshow: false,
                itemWidth: 210,
                minItems: getGridSize(), // use function to pull in initial value
                maxItems: getGridSize() // use function to pull in initial value
            });
        });
    }());
</script>
<!-- Featured Product End-->

app/views/layouts/_footer.html.erb
<!--Footer Part Start-->
<footer id="footer">
	<div class="fpart-inner">
		<div class="social-part">
			<!-- Custom Column Part Start-->
			<div class="custom_column part3">
				<h3>Custom Column</h3>
				<p>
					You can insert any content here.
					<br>
					<br>
					Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s,
					<br>
					<br>
					when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic.
				</p>
			</div>
			<!-- Custom Column Part End-->
			<!-- Twitter Feeds Part Start-->
			<div id="twitter_footer" class="part3">
				<h3>Twitter Feed</h3>
				<ul id="twitter_update_list" class="twitt_icon">
					<script type="text/javascript" src="http://twitter.com/javascripts/blogger.js"></script>
					<script	type="text/javascript" src="https://api.twitter.com/1/statuses/user_timeline.json?screen_name=harnishdesign &amp;callback=twitterCallback2&amp;count=3"></script>
				</ul>
			</div>
			<!-- Twitter Feeds Part End-->
			<!-- Facebook Box Part Start-->
			<div id="facebook" class="part3">
				<h3>Join us on Facebook</h3>
				<div class="line"></div>
				<div id="fb-root"></div>
				<script>
					( function(d, s, id) {
							var js, fjs = d.getElementsByTagName(s)[0];
							if (d.getElementById(id))
								return;
							js = d.createElement(s);
							js.id = id;
							js.src = "http://connect.facebook.net/en_US/all.js#xfbml=1";
							fjs.parentNode.insertBefore(js, fjs);
						}(document, 'script', 'facebook-jssdk'));
				</script>
				<div class="fb-like-box" data-href="http://www.facebook.com/160281810726316" data-width="300" data-show-faces="true" data-stream="false" data-header="false" data-colorscheme="dark" data-connections="16" data-color-scheme="dark" data-border-color="#222222"></div>
			</div>
			<!-- Facebook Box Part End-->
		</div>
		<div class="column">
			<h3>Information</h3>
			<ul>
				<li>
					<%= link_to "About Us",about_us_path %>
				</li>
				<li>
					<%= link_to "Delivery Information",delivery_information_path %>
				</li>
				<li>
					<%= link_to "Privacy Policy",privacy_policy_path %>
				</li>
				<li>
					<a href="elements.html">Elements</a>
				</li>
			</ul>
		</div>
		<div class="column">
			<h3>Customer Service</h3>
			<ul>
				<li>
					<%= link_to "Contact Us",contact_us_path %>
				</li>
				<li>
					<a href="#">Returns</a>
				</li>
			</ul>
		</div>
		<!-- <div class="column">
		<h3>Extras</h3>
		<ul>
		<li>
		<a href="#">Brands</a>
		</li>
		<li>
		<a href="#">Gift Vouchers</a>
		</li>
		<li>
		<a href="#">Affiliates</a>
		</li>
		<li>
		<a href="#">Specials</a>
		</li>
		</ul>
		</div> -->
		<div class="column">
			<h3>My Account</h3>
			<ul>
				<li>
					<a href="about_us">My Account</a>
				</li>
				<li>
					<a href="#">Order History</a>
				</li>
				<li>
					<a href="#">Wish List</a>
				</li>
				<li>
					<a href="#">Newsletter</a>
				</li>
			</ul>
		</div>
		<!-- Contact Details Start-->
		<div class="contact contact_icon">
			<h3>Contact Us</h3>
			<ul>
				<li class="address">
					Central Square, 22 Hoi Wing Road, Tuen Mun, New Delhi, India
				</li>
				<li class="mobile">
					+91 9896989598
				</li>
				<li class="fax">
					+91 9896989598
				</li>
				<li class="email">
					<a href="mailto:info@contact.com">info@contact.com</a>
				</li>
			</ul>
		</div>
		<!-- Contact Details End-->
		<div class="clear"></div>
		<div id="powered">
			<!-- Payment Images Icon Start-->
			<!-- <div class="payments_types part3">
			<img src="image/payment_paypal.png" alt="paypal" title="PayPal"><img src="image/payment_american.png" alt="american-express" title="American Express">
			<img src="image/payment_2checkout.png" alt="2checkout" title="2checkout">
			<img src="image/payment_maestro.png" alt="maestro" title="Maestro">
			<img src="image/payment_discover.png" alt="discover" title="Discover">
			</div> -->
			<!-- Payment Images Icon End-->
			<!-- Powered by Text Start-->
			<div class="powered_text part3">
				<p>
					Polishop Html Template © 2013
					<br />
					Template By <a target="_blank" href="http://harnishdesign.net/">Harnish Design</a>
				</p>
			</div>
			<!-- Powered by Text End-->
			<!-- Follow Social Icons Start-->
			<div class="social part3">
				<%= link_to image_tag("/assets/facebook.png", :border => 0), "http://facebook.com/harnishdesign", {:title => "Facebook"} %>
				<%= link_to image_tag("/assets/twitter.png", :border => 0), "https://twitter.com/#!/harnishdesign", {:title => "Twitter"} %>
				<%= link_to image_tag("/assets/googleplus.png", :border => 0), "#", {:title => "Google+"} %>
				<%= link_to image_tag("/assets/pinterest.png", :border => 0), "#", {:title => "Pinterest"} %>
				<%= link_to image_tag("/assets/rss.png", :border => 0), "#", {:title => "RSS"} %>
				<%= link_to image_tag("/assets/vimeo.png", :border => 0), "http://www.vimeo.com/#", {:title => "Vimeo"} %>
			</div>
			<!-- Follow Social Icons End-->
			<div class="clear"></div>
		</div>
		<!-- Back to Top Button Start-->
		<div class="back-to-top" id="back-top">
			<a title="Back to Top" href="javascript:void(0)" class="backtotop">Top</a>
		</div>
		<!-- Back to Top Button End-->
	</div>
</footer>
<!--Footer Part End-->

app/views/layouts/_header.html.erb
<header id="header">
	<div class="htop">

		<div class="links">
			<% if user_is_signed_in? %>
			<%= link_to "My Account", profile_path %>
			<%= link_to "Sign out", signout_path, :method => "get" %>
			<% elsif admin_is_signed_in? %>
			<%= link_to "My Account", admin_index_path %>
			<%= link_to "Sign out", admin_signout_path, :method => "get" %>
			<% else %>
			<%= link_to "Login", signin_path, :method => "get" %>
			<%= link_to "Register", signUp_path, :method => "get" %>
			<% end %>
		</div>
	</div>

	<section class="hsecond">
		<div id="logo">
			<%= link_to image_tag("/assets/logo.png", :border => 0), root_path, {:title => "Cash shop"} %>
		</div>
		<!--Mini Shopping Cart Start-->

		<div id="cart_code">
			<%= render "layouts/cart"%>
		</div>

		<!--Mini Shopping Cart End-->

		<div class="clear"></div>
	</section>
	<!--Mini Shopping Cart End-->
	<!--Top Menu(Horizontal Categories) Start-->
	<nav id="menu">
		<ul>
			<li class="home">
				<%= link_to image_tag("/assets/home	.png", :border => 0), root_path, {:title => "Home"} %>
			</li>
			<li>
			<li class="categories_hor">
				<%= link_to "Store", {:controller => "application", :action => "store_categories"} %>

				<div>
					<%  @application_categories.each do |category| %>
					<div class="column">
						<b> <%= link_to category["name"], {:controller => "application", :action => "store_sub_categories", :category_id => category["id"]} %></b>

						<div>
							<ul>
								<% sub_categories=get_sub_categories_by_category_id(category["id"]) %>
								<% sub_categories.each do |sub_category| %>
								<% count=get_products_count(sub_category["id"])  %>
								<li>
									<%= link_to sub_category["name"]+"(#{count})", {:controller => "application", :action => "products", :sub_category_id => sub_category["id"]} %>
								</li>
								<% end %>
							</ul>
						</div>
					</div>

					<% end %>
				</div>
			</li>

			<!-- <li>
			<a  href="#">Store</a>
			</li> -->

			<!-- <li>
			<a>My Account</a>

			<div>
			<ul>
			<li>
			<a href="#">My Account</a>
			</li>
			<li>
			<a href="#">Order History</a>
			</li>

			</ul>
			</div>
			</li> -->
			<li>
				<%= link_to "About Us",about_us_path %>

				<!-- <div>
				<ul>
				<li>
				<a href="a#">About Us</a>
				</li>
				<li>
				<a href="#">Delivery Information</a>
				</li>
				<li>
				<a href="#">Privacy Policy</a>
				</li>
				<li>
				<a href="#">Elements</a>
				</li>
				</ul>
				</div> -->
			</li>

			<li>
				<%= link_to "Contact Us",contact_us_path %>
			</li>
			<% if (user_is_signed_in?)   %>
			<li>
				<a>MOre</a>

				<div>
					<ul>
						<li>
							<%= link_to "Edit profile", edit_profile_path ,:method=>"get"%>
						</li>
						<li>
							<%= link_to "Change password", change_password_path ,:method=>"get"%>
						</li>
						<li>
							<%= link_to "Expenses", expenses_path ,:method=>"get"%>
						</li>
					</ul>
				</div>
			</li>
			<% end %>
		</ul>
	</nav>
	<!--Top Menu(Horizontal Categories) End-->
</header>

app/views/layouts/_latest_products.html.erb
<% last_products=get_last_5_products %>
<% if last_products && !last_products.empty? %>
    <!--Latest Product Start-->
    <div class="box">
      <div class="box-heading">
        Latest
      </div>
      <div class="box-content">
        <div class="box-product">
          <div class="flexslider">
            <ul class="slides">
              <% last_products.each do |product| %>
                  <li>
                    <div class="slide-inner">
                      <div class="image">
                        <% if File.exist?("app/assets/images/data/products/#{product["id"]}") %>
                            <% selected_product_image=get_product_images(product["id"]) %>
                            <%= link_to image_tag("data/products/#{product["id"]}/#{selected_product_image[0]}", :alt => "#{product["name"]}"), {:controller => "application", :action => "product", :product_id => product["id"]} %>

                        <% else %>
                            <%= link_to image_tag("/assets/logo.png"), {:controller => "application", :action => "product", :product_id => product["id"]} %>
                        <% end %>
                      </div>
                      <div class="name"><a href="product.html"><%= product["name"] %></a></div>
                      <% if product["offer"] && product["offer"]>0 %>
                          <% new_price=product["price"]- (product["price"]* (product["offer"] / 100)) %>
                          <div class="price"><span class="price-old"><%= product["price"] %> $</span>
                            <span class="price-new"><%= new_price %> $</span></div>
                      <% else %>
                          <div class="price"><%= product["price"] %> $</div>
                      <% end %>
                      <div class="clear"></div>
                    </div>
                  </li>
              <% end %>

            </ul>
          </div>
        </div>
      </div>
    </div>
    <!--Latest Product end-->
<% end %>

app/views/layouts/_left_column.html.erb
<!--Category Start -->
<div class="box">
  <div class="box-heading"><%=  link_to "Categories", {:controller => "application", :action => "store_categories"} %></div>
  <div class="box-content box-category">
    <ul id="cat_accordion">
      <% @application_categories.each do |category| %>
          <li ><b>
            <%= link_to category["name"], {:controller => "application", :action => "store_sub_categories", :category_id => category["id"]} %>
            </b> <span class="down"></span>
              <% sub_categories=get_sub_categories_by_category_id(category["id"]) %>
              <% sub_categories.each do |sub_category| %>
                <% count= get_products_count(sub_category["id"]) %>
                <% if count>0 %>
                  <li class="custom_id26">
                    <%= link_to sub_category["name"]+"(#{count})", {:controller => "application", :action => "products", :sub_category_id => sub_category["id"]} %>
                  </li>
                <% end %>
            <% end %>
          </li>
      <% end %>
    </ul>
  </div>
</div>
<%= render 'layouts/latest_products'%>
<script type="text/javascript" src="/assets/jquery.dcjqaccordion.js"></script>
<!--Category End -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>NetworkingMarketing</title>
		<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
		<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
		<%= javascript_include_tag :defaults %>
		<%= csrf_meta_tags %>

	</head>
	<body>

		<div class="wrapper-box">
			<div class="main-wrapper">
				<div id="heade_rails">
					<%= render 'layouts/header'%>
					<br/>
				</div>
				<%= yield %>
				<br/>
				<%= render 'layouts/footer'%>

			</div>
		</div>

	</body>
</html>

app/views/layouts/remove_product_from_cart.js.erb
$("#cart").html("<%= escape_javascript(render "layouts/teastCart") %>");